### ISSUE TITLE
 Logcat show nothing

### ISSUE THREAD

**Issue by iwanglian** [tony19/logback-android#100]
Hi,  @tony19  I use this lib as guide, but no log show in Logcat ,or no file generated.

I use Android Studio , put the 2 jar in libs, and append this in  build.gradle
        compile files('libs/logback-android-1.1.1-4.jar')
        compile files('libs/slf4j-api-1.7.6.jar')

And the copy the xml into assets/logback.xml of my project.
And in MainActivity, I have the code
             Logger log = LoggerFactory.getLogger(MainActivity.class);
            log.info("***************onTabChanged", String.valueOf(tabId));

**Comment by iwanglian** [comment]
I use the android studio to create the folder Asserts, and it works.

But the file appender not work.

**Comment by tony19** [comment]
Unfortunately, this report does not have enough info. How exactly does the FileAppender "not work"? What does your logback configuration look like?

Also try the [example code](https://github.com/tony19/logback-android/wiki/Appender-Notes#fileappender-rollingfileappender).
