### ISSUE TITLE
Using with Gradle?

### ISSUE THREAD

**Issue by cryo75** [tony19/logback-android#101]
How can logback-android be used with Gradle (Android Studio)?

**Comment by JasonSheedy** [comment]
So far I have local console logging working using the following:

```
// logging
compile 'org.slf4j:slf4j-api:1.7.13'
compile 'com.github.tony19:logback-android-core:1.1.1-4'
compile 'com.github.tony19:logback-android-classic:1.1.1-4'
```

**Comment by tony19** [comment]
@cryo75, Were you simply looking for the Gradle config? (If so, it looks like @JasonSheedy answered for me. Thanks Jason!)

**Comment by JasonSheedy** [comment]
No worries @tony19 :)
