### ISSUE TITLE
Logcat appender does not show stacktrace when the message ends with a newline

### ISSUE THREAD

**Issue by bmaslakov** [tony19/logback-android#102]
I set up logcat appender pretty much like in example:

    public static void setupLogcatAppender() {
        LoggerContext lc = (LoggerContext) LoggerFactory.getILoggerFactory();

        // setup LogcatAppender
        PatternLayoutEncoder encoder2 = new PatternLayoutEncoder();
        encoder2.setContext(lc);
        encoder2.setPattern("[%thread] %method\\(\\): %msg%n");
        encoder2.start();

        LogcatAppender logcatAppender = new LogcatAppender();
        logcatAppender.setContext(lc);
        logcatAppender.setEncoder(encoder2);
        logcatAppender.start();

        // add the newly created appenders to the root logger;
        // qualify Logger to disambiguate from org.slf4j.Logger
        Logger root = (Logger) LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME);
        root.addAppender(logcatAppender);
    }

And this is how I handle exception:

    try {
        String a = null;
        a.toString();
    } catch (Exception ex) {
        LoggerFactory.getLogger(getClass()).debug("v=0\n" +
                "o=- 1815849 0 IN IP4 194.67.15.181\n" +
                "s=Cisco SDP 0\n" +
                "c=IN IP4 194.67.15.181\n" +
                "t=0 0\n" +
                "m=audio 20062 RTP/AVP 99 18 101 100\n" +
                "a=rtpmap:99 G.729b/8000\n" +
                "a=rtpmap:101 telephone-event/8000\n" +
                "a=fmtp:101 0-15\n" +
                "a=rtpmap:100 X-NSE/8000\n" +
                "a=fmtp:100 200-202\n", ex);
    }

In this case I do not see the stacktrace in logcat, only the message:

    12-11 15:13:45.001 6348-6348/c.t.a D/c.t.a.LaunchActivity: [main] onCreate(): v=0
           o=- 1815849 0 IN IP4 194.67.15.181
           s=Cisco SDP 0
           c=IN IP4 194.67.15.181
           t=0 0
           m=audio 20062 RTP/AVP 99 18 101 100
           a=rtpmap:99 G.729b/8000
           a=rtpmap:101 telephone-event/8000
           a=fmtp:101 0-15
           a=rtpmap:100 X-NSE/8000
           a=fmtp:100 200-202

However, If I the message does not end with "\n":

    LoggerFactory.getLogger(getClass()).debug("v=0\n" +
            "o=- 1815849 0 IN IP4 194.67.15.181\n" +
            "s=Cisco SDP 0\n" +
            "c=IN IP4 194.67.15.181\n" +
            "t=0 0\n" +
            "m=audio 20062 RTP/AVP 99 18 101 100\n" +
            "a=rtpmap:99 G.729b/8000\n" +
            "a=rtpmap:101 telephone-event/8000\n" +
            "a=fmtp:101 0-15\n" +
            "a=rtpmap:100 X-NSE/8000\n" +
            "a=fmtp:100 200-202", ex);

I get the complete message and exception trace.

    12-11 15:17:37.486 9623-9623/c.t.a D/c.t.a.LaunchActivity: [main] onCreate(): v=0
       o=- 1815849 0 IN IP4 194.67.15.181
       s=Cisco SDP 0
       c=IN IP4 194.67.15.181
       t=0 0
       m=audio 20062 RTP/AVP 99 18 101 100
       a=rtpmap:99 G.729b/8000
       a=rtpmap:101 telephone-event/8000
       a=fmtp:101 0-15
       a=rtpmap:100 X-NSE/8000
       a=fmtp:100 200-202
       java.lang.NullPointerException: null
        at c.t.a.LaunchActivity.onCreate(LaunchActivity.java:180) ~[na:0.0]
        at android.app.Activity.performCreate(Activity.java:5231) ~[na:0.0]
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) ~[na:0.0]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169) ~[na:0.0]
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271) ~[na:0.0]
        at android.app.ActivityThread.access$800(ActivityThread.java:144) ~[na:0.0]
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205) ~[na:0.0]
        at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
        at android.os.Looper.loop(Looper.java:136) ~[na:0.0]
        at android.app.ActivityThread.main(ActivityThread.java:5146) ~[na:0.0]
        at java.lang.reflect.Method.invokeNative(Native Method) ~[na:0.0]
        at java.lang.reflect.Method.invoke(Method.java:515) ~[na:0.0]
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732) ~[na:0.0]
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566) ~[na:0.0]
        at dalvik.system.NativeStart.main(Native Method) ~[na:0.0]

**Comment by tony19** [comment]
I cannot reproduce this bug with the code below (includes your sample above). What versions are you running with?

Test environment
* Android M
* logback-android 1.1.1-4
* slf4j-api 1.7.13

build.gradle
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "21.1.1"

    defaultConfig {
        applicationId "com.github.tony19.logback_android_github_issue102"
        minSdkVersion 23
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    testCompile 'org.robolectric:robolectric:3.0'
    compile 'com.android.support:appcompat-v7:23.1.1'

    compile 'com.github.tony19:logback-android-core:1.1.1-4'
    compile ('com.github.tony19:logback-android-classic:1.1.1-4') {
        exclude group: 'com.google.android', module: 'android'
    }
    compile 'org.slf4j:slf4j-api:1.7.13'
}
```

MainActivity.java
```java
package com.github.tony19.logback_android_github_issue102;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

import org.slf4j.LoggerFactory;

import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.LoggerContext;
import ch.qos.logback.classic.android.LogcatAppender;
import ch.qos.logback.classic.encoder.PatternLayoutEncoder;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        setupLogcatAppender();
        try {
            String a = null;
            a.toString();
        } catch (Exception ex) {
            LoggerFactory.getLogger(getClass()).debug("v=0\n" +
                    "o=- 1815849 0 IN IP4 194.67.15.181\n" +
                    "s=Cisco SDP 0\n" +
                    "c=IN IP4 194.67.15.181\n" +
                    "t=0 0\n" +
                    "m=audio 20062 RTP/AVP 99 18 101 100\n" +
                    "a=rtpmap:99 G.729b/8000\n" +
                    "a=rtpmap:101 telephone-event/8000\n" +
                    "a=fmtp:101 0-15\n" +
                    "a=rtpmap:100 X-NSE/8000\n" +
                    "a=fmtp:100 200-202\n", ex);
        }
    }

    public static void setupLogcatAppender() {
        LoggerContext lc = (LoggerContext) LoggerFactory.getILoggerFactory();

        // setup LogcatAppender
        PatternLayoutEncoder encoder2 = new PatternLayoutEncoder();
        encoder2.setContext(lc);
        encoder2.setPattern("[%thread] %method\\(\\): %msg%n");
        encoder2.start();

        LogcatAppender logcatAppender = new LogcatAppender();
        logcatAppender.setContext(lc);
        logcatAppender.setEncoder(encoder2);
        logcatAppender.start();

        // add the newly created appenders to the root logger;
        // qualify Logger to disambiguate from org.slf4j.Logger
        Logger root = (Logger) LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME);
        root.addAppender(logcatAppender);
    }
}
```

LogcatAppenderLogsException.java
```java
package com.github.tony19.logback_android_github_issue102;

import android.util.Log;

import java.util.List;

import static junit.framework.Assert.assertTrue;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.shadows.ShadowLog;

import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.LoggerContext;
import ch.qos.logback.classic.android.LogcatAppender;
import ch.qos.logback.classic.encoder.PatternLayoutEncoder;

/**
 * This verifies that the LogcatAppender logs a given throwable (Github Issue #102).
 * @link https://github.com/tony19/logback-android/issues/102
 */
@RunWith(RobolectricTestRunner.class)
public class LogcatAppenderLogsException {

    private LoggerContext lc = new LoggerContext();
    private Logger root = lc.getLogger(Logger.ROOT_LOGGER_NAME);
    private Logger logger = lc.getLogger(LogcatAppenderLogsException.class);
    private final String MESSAGE = "v=0\n" +
            "o=- 1815849 0 IN IP4 194.67.15.181\n" +
            "s=Cisco SDP 0\n" +
            "c=IN IP4 194.67.15.181\n" +
            "t=0 0\n" +
            "m=audio 20062 RTP/AVP 99 18 101 100\n" +
            "a=rtpmap:99 G.729b/8000\n" +
            "a=rtpmap:101 telephone-event/8000\n" +
            "a=fmtp:101 0-15\n" +
            "a=rtpmap:100 X-NSE/8000\n" +
            "a=fmtp:100 200-202";

    @Before
    public void setup() {
        //LoggerContext lc = (LoggerContext) LoggerFactory.getILoggerFactory();

        // setup LogcatAppender
        PatternLayoutEncoder encoder2 = new PatternLayoutEncoder();
        encoder2.setContext(lc);
        encoder2.setPattern("[%thread] %method\\(\\): %msg%n");
        encoder2.start();

        LogcatAppender logcatAppender = new LogcatAppender();
        logcatAppender.setContext(lc);
        logcatAppender.setEncoder(encoder2);
        logcatAppender.start();

        // add the newly created appenders to the root logger;
        // qualify Logger to disambiguate from org.slf4j.Logger
        //Logger root = (Logger) LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME);
        root.detachAndStopAllAppenders();
        root.addAppender(logcatAppender);

        ShadowLog.reset();
    }

    @Test
    public void trailingNewLine() {
        logger.debug(MESSAGE + "\n", new NullPointerException());
        assertLogcatContains(Log.DEBUG, NullPointerException.class.getName());
    }

    @Test
    public void noTrailingNewLine() {
        logger.debug(MESSAGE, new NullPointerException());
        assertLogcatContains(Log.DEBUG, NullPointerException.class.getName());
    }

    private void assertLogcatContains(int level, String errorMessage) {
        List<ShadowLog.LogItem> logs = ShadowLog.getLogsForTag(LogcatAppenderLogsException.class.getName());
        assertTrue(logcatContains(logs, level, errorMessage));
    }

    private boolean logcatContains(List<ShadowLog.LogItem> logs, int level, String errorMessage) {
        boolean found = false;
        for (ShadowLog.LogItem s : logs) {
            if (level == s.type) {
                if (s.msg.contains(errorMessage)) {
                    found = true;
                    break;
                }
            }
        }
        return found;
    }
}
```
