### ISSUE TITLE
Max file size + single file only => truncate rollover policy

### ISSUE THREAD

**Issue by MFlisar** [tony19/logback-android#105]
Is it possible to somehow have a setup that works with one log file and just removes the last lines in this single log if the file is to large or has too many lines?

I could think of some setup like following:
1) File Size Based
If size exceeds 1MB, remove have of the files content to get it down to 0.5MB again
2) Line Count Based
If file exceeds 10000 lines, remove the last 5000 lines to get it down to 5000 lines again.

**Why?**

I want to have ONE log file only, I don't need older log files at all but it's important that this log file does contain the most recent data. 

**Solution1 - not perfect**

I used a `SizeBasedTriggeringPolicy` with a `FixedWindowRollingPolicy` with `min/max index = 1` but this has one side effect: the log file may sometimes be rolled over shortly before a crash and then the important data is not in the last log file anymore...

**Solution2 - don't use and rolling policy + manually truncate the file**

Whenever I start my app I check how long the log file is a truncate it manually...

**Question**

Is there some setup possible to get my desired behaviour?

**Comment by tony19** [comment]
Not that I'm aware of. You could [roll your own appender](http://logback.qos.ch/manual/appenders.html#WriteYourOwnAppender) to accomplish this.
