### ISSUE TITLE
There is no way to get real path for FileAppender

### ISSUE THREAD

**Issue by stari4ek** [tony19/logback-android#106]
It looks like current implementation is a bit tricky:

```
private String getAbsoluteFilePath(String filename) {
    // In Android, relative paths created with File() are relative
    // to root, so fix it by prefixing the path to the app's "files"
    // directory.
    // This transformation is rather expensive, since it involves loading the
    // Android manifest from the APK (which is a ZIP file), and parsing it to
    // retrieve the application package name. This should be avoided if
    // possible as it may perceptibly delay the app launch time.
    if (EnvUtil.isAndroidOS() && !new File(filename).isAbsolute()) {
      String dataDir = context.getProperty(CoreConstants.DATA_DIR_KEY);
      filename = FileUtil.prefixRelativePath(dataDir, filename);
    }
    return filename;
  }
```

So, if we need file path from outside we can't get it using `getFile` cause it doesn't apply this hidden logic. The only way right now is hard-code prefixing with `CoreConstants.DATA_DIR_KEY`

**Comment by tony19** [comment]
One solution might be to update [`FileAppender#getFile()`](https://github.com/tony19/logback-android/blob/0742fdb/logback-core/src/main/java/ch/qos/logback/core/FileAppender.java#L89-L91) to return the absolute path that is determined by `getAbsoluteFilePath()`. Is that what you're looking for?

**Comment by stari4ek** [comment]
yes, it solves the problem, but it looks more like a hack cause _setFile != getFile_
