### ISSUE TITLE
Format LogcatAppender TAG and Content with fixed sizes all together

### ISSUE THREAD

**Issue by XabierGoros** [tony19/logback-android#107]
Is there any way to format Logcat's TAG and Content with fixed sizes? Let me explain it a little bit more:

I have the following logback.xml configuration:

```
<appender name="LOGCAT" class="ch.qos.logback.classic.android.LogcatAppender">
    <checkLoggable>false</checkLoggable>
    <tagEncoder>
        <pattern>%-12logger{12}</pattern>
    </tagEncoder>
    <encoder>
        <pattern>- Thread-%-20thread - %msg%n</pattern>
    </encoder>
</appender>
```

What I get with it is:
```
D/c.s.j.d.c.c.s.MyDummyCustomClassTest: - Thread-AsyncTask #1
D/c.s.j.m.MyDummyManagerTest: - Thread-main
```
I don't understand why having `<pattern>%-12logger{12}</pattern>` I get those TAG's lengths, but anyway, what I'd like to get is:

```
D/c.s.j.d.c.c.s.MyDummyCustomClassTest: - Thread-AsyncTask #1
D/c.s.j.m.MyDummyManagerTest          : - Thread-main
```

Is there any way? Am I doing anything wrong with the TAG configuration?

**Comment by tony19** [comment]
logcat itself (and not logback-android) is trimming the trailing whitespace from the tag (try `Log.d("foo     ", "bar");`). Experimentation shows that leading whitespace is not trimmed, so left-padding might be your only option.
