### ISSUE TITLE
ClassNotFoundException: ... on path: DexPathList[[zip file "/data/app/com.***.apk"]

### ISSUE THREAD

**Issue by hyeongsik-won** [tony19/logback-android#108]
Hi, tony19
Thank you for your logback-android.

I'm trying to add my own Appender to my app but I'm facing a  problem.

This is the configuration on logback.xml.
`<appender name="NELO" class="com.myapp.log.logback.appender.CustomAppender"></appender>
`

This is the error message.
`ClassNotFoundException: Didn't find class "com.myapp.log.logback.appender.CustomAppender" on path: DexPathList[[zip file "/data/app/com.myapp.myapp.apk"]
`

The "com.myapp.log.logback.appender" is correct package path.

Help for me. Thank you.

**Comment by hyeongsik-won** [comment]
I sovled this problem. I put the CustomAppender on "ch.qos.logback.core.rolling". I don't know why. Do you know about the reason?

**Comment by tony19** [comment]
I don't know why your appender would need to be inside of logback's package. Is it possible that your appender is being wiped out by Proguard?

**Comment by hyeongsik-won** [comment]
I don't use Proguard. 
The "ch.qos.logback.core.rolling" is in my app. I created same package.
Thank you your answer.
