### ISSUE TITLE
Rolling

### ISSUE THREAD

**Issue by mgohin** [tony19/logback-android#110]
UPDATED TOPIC

Hi,

can't make rolling working, still getting `timeBasedlogFile.log` and nothing else, any idea ?

    <configuration debug="true">
        <appender name="logcat" class="ch.qos.logback.classic.android.LogcatAppender">
            <encoder>
                <pattern>%msg</pattern>
            </encoder>
        </appender>
    
        <appender name="rotation" class="ch.qos.logback.core.rolling.RollingFileAppender">
            <file>timeBasedlogFile.log</file>
            <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
                
                <fileNamePattern>timeBasedlogFile.%d{yyyy-MM-dd-HH-mm}.log</fileNamePattern>
                <maxHistory>30</maxHistory>
            </rollingPolicy>
    
            <encoder>
                <pattern>%relative [%thread] %-5level %logger{35} - %msg%n</pattern>
            </encoder>
        </appender>
    
        <root level="DEBUG">
            <appender-ref ref="logcat" />
            <appender-ref ref="rotation" />
        </root>
    </configuration>

Here are log files

    03-14 09:52:56.481 16193-16193/com.myapp I/System.out: 09:52:56,446 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [assets/logback.xml] at [assets/logback.xml]
	03-14 09:52:56.482 16193-16193/com.myapp I/System.out: 09:52:56,481 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.android.LogcatAppender]
	03-14 09:52:56.483 16193-16193/com.myapp I/System.out: 09:52:56,482 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [logcat]
	03-14 09:52:56.492 16193-16193/com.myapp I/System.out: 09:52:56,491 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
	03-14 09:52:56.520 16193-16193/com.myapp I/System.out: 09:52:56,520 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
	03-14 09:52:56.523 16193-16193/com.myapp I/System.out: 09:52:56,522 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [rotation]
	03-14 09:52:56.549 16193-16193/com.myapp I/System.out: 09:52:56,548 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
	03-14 09:52:56.550 16193-16193/com.myapp I/System.out: 09:52:56,550 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern timeBasedlogFile.%d{yyyy-MM-dd-HH-mm}.log for the active file
	03-14 09:52:56.554 16193-16193/com.myapp I/System.out: 09:52:56,553 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd-HH-mm' from file name pattern 'timeBasedlogFile.%d{yyyy-MM-dd-HH-mm}.log'.
	03-14 09:52:56.554 16193-16193/com.myapp I/System.out: 09:52:56,554 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over every minute.
	03-14 09:52:56.554 16193-16193/com.myapp I/System.out: 09:52:56,554 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Mon Mar 14 09:52:56 GMT+01:00 2016
	03-14 09:52:56.559 16193-16193/com.myapp I/System.out: 09:52:56,558 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
	03-14 09:52:56.568 16193-16193/com.myapp I/System.out: 09:52:56,568 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[rotation] - Active log file name: timeBasedlogFile.log
	03-14 09:52:56.595 16193-16193/com.myapp I/System.out: 09:52:56,594 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[rotation] - File property is set to [/data/data/com.myapp/files/timeBasedlogFile.log]
	03-14 09:52:56.596 16193-16193/com.myapp I/System.out: 09:52:56,596 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
	03-14 09:52:56.597 16193-16193/com.myapp I/System.out: 09:52:56,597 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [file]. Did you define it below instead of above in the configuration file?
	03-14 09:52:56.597 16193-16193/com.myapp I/System.out: 09:52:56,597 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - See http://logback.qos.ch/codes.html#appender_order for more details.
	03-14 09:52:56.598 16193-16193/com.myapp I/System.out: 09:52:56,598 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [logcat] to Logger[ROOT]
	03-14 09:52:56.599 16193-16193/com.myapp I/System.out: 09:52:56,598 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [rotation] to Logger[ROOT]
	03-14 09:52:56.599 16193-16193/com.myapp I/System.out: 09:52:56,599 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
	03-14 09:52:56.600 16193-16193/com.myapp I/System.out: 09:52:56,600 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@f9316d - Registering current configuration as safe fallback point

When trying to add logs on a minute rolling I got this, no more explanation :

    WARN in ch.qos.logback.core.rolling.RollingFileAppender[rotation] - RolloverFailure occurred. Deferring rollover

**Comment by tony19** [comment]
Try using an absolute file path in `<fileNamePattern>`:
https://github.com/tony19/logback-android/wiki/Appender-Notes#fileappender-rollingfileappender

**Comment by mgohin** [comment]
It's not in my xml piece of code but it's in my project, I tried :(

**Comment by tony19** [comment]
Sorry I don't understand what you're saying.

**Comment by tony19** [comment]
Your logback configuration shows relative file paths for `<file>` and `<fileNamePattern>`, which seems to be the problem. I confirmed that changing *both* to absolute paths resolves the issue.

```xml
  <appender name="rotation" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <file>${DATA_DIR}/timeBasedlogFile.log</file>
    <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
      <!-- daily rollover -->
      <fileNamePattern>${DATA_DIR}/timeBasedlogFile.%d{yyyy-MM-dd-HH-mm-ss}.log</fileNamePattern>
      <maxHistory>30</maxHistory>
    </rollingPolicy>

    <encoder>
      <pattern>%relative [%thread] %-5level %logger{35} - %msg%n</pattern>
    </encoder>
  </appender>
```

**Comment by mgohin** [comment]
Sorry my answer wasn't sent.
Yep I tried with full path.

What is in your `${DATA_DIR}` ?

**Comment by tony19** [comment]
You tried the configuration I provided above, and it still resulted in the same failure?

That's one of the special variables (unfortunately undocumented) -- equal to `/data/data/<package-name>/files`. Its usage does incur a one-time performance hit (which may or may not be negligible to your app) as it requires parsing AndroidManifest.xml in order to determine the package name. If you prefer to avoid the hit (and especially if the path doesn't change), just hard-code it.

**Comment by mgohin** [comment]
It's working, sorry I edited my post :)
