### ISSUE TITLE
Unable to write to papertrail from Android app

### ISSUE THREAD

**Issue by pratiksharma821** [tony19/logback-android#111]
HI

I am using the this thing in my Android app but not able to send logs to papertrail.

I am getting this warn.
**03-13 15:47:59.569: I/System.out(15401): 15:47:59,568 |-WARN in ch.qos.logback.classic.net.SyslogAppender[PAPERTRAIL] - Attempted to append to non started appender [PAPERTRAIL].**

**[1] My logback.xml file under assets folder.**

```
<?xml version="1.0" encoding="UTF-8"?>

<configuration debug="true">
  <appender name="LOGCAT" class="ch.qos.logback.classic.android.LogcatAppender" >
    <tagEncoder>
       <pattern>%logger{0}</pattern>
    </tagEncoder>
    <encoder>
      <pattern>[ %thread ] %msg%n</pattern>
    </encoder>
  </appender>

  <appender name="PAPERTRAIL" class="ch.qos.logback.classic.net.SyslogAppender">
    <suffixPattern>logback SyslogAppender: %-5level %logger{35}: %m%n%xEx</suffixPattern>
    <syslogHost>logs3.papertrailapp.com</syslogHost>
    <port>12256</port>
    <facility>MyApp</facility>


    <!-- use lazy initialization so that network connection is not opened until first write -->
    <lazy>true</lazy>


  </appender>

  <appender name="ASYNC" class="ch.qos.logback.classic.AsyncAppender">
    <appender-ref ref="PAPERTRAIL" />
  </appender>

  <root level="DEBUG">
    <appender-ref ref="ASYNC" />
    <appender-ref ref="LOGCAT" />
  </root>

</configuration>
```

**[2] In my activity.**

```
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
........
........

Logger LOG = LoggerFactory.getLogger(MainActivity.class);
LOG.info(log_message);
```

Help me.

**Comment by tony19** [comment]
The debug flag in `<configuration debug="true">` causes the result of the logback configuration, including errors, to output to logcat:

```
I/System.out: 06:51:52,704 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [assets/logback.xml] at [assets/logback.xml]
I/System.out: 06:51:52,711 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.android.LogcatAppender]
I/System.out: 06:51:52,712 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [LOGCAT]
I/System.out: 06:51:52,713 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [tagEncoder] property
I/System.out: 06:51:52,719 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
I/System.out: 06:51:52,722 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.net.SyslogAppender]
I/System.out: 06:51:52,722 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [PAPERTRAIL]
I/System.out: 06:51:52,732 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@22:14 - RuntimeException in Action for tag [appender] java.lang.IllegalArgumentException: MyApp is not a valid syslog facility string
```

The valid syslog facility strings are defined in the [logback manual](http://logback.qos.ch/manual/appenders.html#syslogFacility).

**Comment by pratiksharma821** [comment]
Thank you very much it is working now.

**Comment by pratiksharma821** [comment]
I just want to ask you one thing.

```
Mar 16 10:29:24 localhost Android-App:  text message 
Mar 16 10:29:44 localhost Android-App:  text message

```
This is log I can see at Papertrail events.

Can I change this "localhost" value with some dynamic value like devicename or something?

 Thanks

**Comment by roxxydev** [comment]
I'd like to know how to change that "localhost" text too as it is what is seen in Papertrail logs. Do I need to add any XML tags to my logback config?

Here's my logback config

`<configuration debug="true">
    <appender name="PAPERTRAIL" class="ch.qos.logback.classic.net.SyslogAppender">
        <suffixPattern>TestPapertrail %-5level %logger{35}: %m%n%xEx</suffixPattern>
        <syslogHost>${PAPERTRAIL_HOST}</syslogHost>
        <port>${PAPERTRAIL_PORT}</port>
        <facility>USER</facility>
        
        <lazy>true</lazy>
    </appender>

    <appender name="ASYNC" class="ch.qos.logback.classic.AsyncAppender">
        <appender-ref ref="PAPERTRAIL" />
    </appender>

    <root level="DEBUG">
        <appender-ref ref="ASYNC" />
    </root>
</configuration>`
