### ISSUE TITLE
AsyncAppender usage

### ISSUE THREAD

**Issue by paruntha** [tony19/logback-android#115]
Quick question about shutting down the AysncAppender
https://github.com/tony19/logback-android/wiki/Appender-Notes#asyncappender

I noticed you said you should call it on the onDestroy method. Would that mean for all the activities and services in live in the same application have this call below on all the onDestory methods?

LoggerContext loggerContext = (LoggerContext) LoggerFactory.getILoggerFactory();
loggerContext.stop();

Is this call even needed?

Dont' think can use the hook right?

**Comment by tony19** [comment]
It's only needed in activities/services that create a logger context with an `AsyncAppender`.
