### ISSUE TITLE
documentation:  on existing project NoClassDefFoundError - LoggerFactory

### ISSUE THREAD

**Issue by MikeMitterer** [tony19/logback-android#116]
Thanks for your lib - it works great. 
I had a minor issue when I added LB4A to an existing app - ClassNotFound (LoggerFactory)
I think it's because of the incremental dex compiler - not sure?

I had to gradle#clean and gradle#build - now it works like a charme!
Maybe you can add this to your README?

**Comment by rwoloszyn** [comment]
@MikeMitterer  post stacktrace, maybe I can help. I had similar problem some time ago.

**Comment by tony19** [comment]
Sounds like a gradle build issue. Please feel free to comment if you can provide steps to reproduce.
