### ISSUE TITLE
Rollover in internal storage fails

### ISSUE THREAD

**Issue by stamanuel** [tony19/logback-android#117]
i am on android api lvl 23, and wanted to store the logs in the internal application folder.

i configured the folder path as "logs/", and the logging itself is working fine, and the logs get written into the logfile. but the rollover is not working when the destination is in the internal folder, there may be a problem with access rights because the logger tries to rename the file?

**Comment by tony19** [comment]
I'm assuming you're using a relative path for the rollover filename pattern (which seems to be a relatively common problem -- #110). Use an absolute path as shown below.

```xml
  <appender name="rotation" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <file>${DATA_DIR}/timeBasedlogFile.log</file>
    <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
      <!-- daily rollover -->
      <fileNamePattern>${DATA_DIR}/timeBasedlogFile.%d{yyyy-MM-dd-HH-mm}.log</fileNamePattern>
      <maxHistory>30</maxHistory>
    </rollingPolicy>

    <encoder>
      <pattern>%relative [%thread] %-5level %logger{35} - %msg%n</pattern>
    </encoder>
  </appender>
```

**Comment by stamanuel** [comment]
thx for helping out here, was not aware that ${DATA_DIR} was there, and was confused because the normal logging was working when using just "logs/" as path. it just failed on the rollover.
