### ISSUE TITLE
Conditional Expressions in XML

### ISSUE THREAD

**Issue by p-andreas** [tony19/logback-android#119]
Thanks for your lib - I am quite happy so far.
Currently I am having one issue with the library: My use-case requires me to use different log appenders for different build-types or build-flavors. 
Since the library does not support conditional expressions I am forced to use a programmatic approach. 

I want to get rid of the programmatic approach because it is quite error prone and I can't reuse it properly in other java (non Android) projects.

Can you point me in the correct way to port the conditional Expressions to android?

**Comment by tony19** [comment]
Assuming you only need conditional system-wide logback config (and not fine-grain logger control within the system), I think a combination of the following would work:

 * Setup [sourcesets for your build variants](https://developer.android.com/studio/build/build-variants.html#sourcesets), and supply a variant of `logback.xml` in each sourceset.
 * Use [initialization search path](https://github.com/tony19/logback-android/wiki#initialization-search-path) to specify optional config files (e.g., for different flavors).

```xml
<configuration>
  <includes>
    <!-- this file is only available in dev builds -->
    <include resource="assets/config/logback-dev.xml"/>

    <!-- default logback config -->
    <include resource="assets/config/logback.xml"/>
  </includes>
</configuration>
```

**Comment by p-andreas** [comment]
Thanks a lot for your fast reply - i will give that a shot.  You are correct; For my use-case this method should work sufficiently.

**Comment by hb0** [comment]
As I found this issue through Google, a short feedback:

For me it worked to simply move the logback.xml file to src/debug/assets/ instead of src/assets to only have the config active in the debug BuildVariant.
