### ISSUE TITLE
Unable logging when use logback-android

### ISSUE THREAD

**Issue by haghpanah** [tony19/logback-android#120]
I am trying to change my logging library from `logback` to `logback-android` but it sounds like I've made something wrong. In my android project:

**AndroidManifest.xml**

```
<uses-sdk android:minSdkVersion="14" android:targetSdkVersion="14" />

<logback>
    <configuration>
        <appender
            name="LOGCAT"
            class="ch.qos.logback.classic.android.LogcatAppender">
            <tagEncoder>
                <pattern>%logger{0}</pattern>
            </tagEncoder>
            <encoder>
                <pattern>blahblah: [%method] > %msg%n</pattern>
            </encoder>
        </appender>
        <root level="TRACE">
            <appender-ref ref="LOGCAT"/>
        </root>
    </configuration>
</logback>

<application
    android:label="@string/custom_app_name" android:debuggable="true"
    android:icon="@drawable/app_icon"
    android:name="blah.blah"
    android:allowBackup="false"
    android:theme="@android:style/Theme.Holo.Light.NoActionBar">
</application>
```
and pom file in case 1,

```
<dependencies>
    ...
    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>${org.slf4j}</version>
        <scope>compile</scope>
    </dependency>
    <dependency>
        <groupId>ch.qos.logback</groupId>
        <artifactId>logback-android</artifactId>
        <version>${ch.qos.logback}</version>
    </dependency>
    ...
</dependencies>
```

and pom file in case 2,

```
<dependencies>
    ...
    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>${org.slf4j}</version>
        <scope>compile</scope>
    </dependency>
    <dependency>
        <groupId>com.github.tony19</groupId>
        <artifactId>logback-android-core</artifactId>
        <version>${logback-android-core}</version>
    </dependency>
    <dependency>
        <groupId>com.github.tony19</groupId>
        <artifactId>logback-android-classic</artifactId>
        <version>${logback-android-classic}</version>
    </dependency>
    ...
</dependencies>
```

and in both cases

```
<properties>
    <org.slf4j>1.7.21</org.slf4j>
    <ch.qos.logback>1.0.6-1</ch.qos.logback>
    <logback-android-core>1.1.1-5</logback-android-core>
    <logback-android-classic>1.1.1-5</logback-android-classic>
</properties>

```

and the code

```
private static final org.slf4j.Logger logger = org.slf4j.LoggerFactory.getLogger(Tester.class);

@Override
public void onCreate(Bundle savedInstanceState)
{
    super.onCreate(savedInstanceState);
    setContentView(R.layout.test_tester);

    findViewById(R.id.btnTest).setOnClickListener(new View.OnClickListener()
    {
        @Override
        public void onClick(View view)
        {
            logger.debug("OK!");
        }
    });
}
```

Now if I use pom (1) (and therefore `logback`) then everything is fine and I receive the logs in `LOGCAT` window but if I change the dependencies to `logback-android` as shown in pom(2) nothing happens and it sounds like there is no logging any longer.

What's wrong with that?

**Comment by tony19** [comment]
I'm surprised if case 1 worked at all because you're using the wrong `groupId` (i.e., there is no `ch.qos.logback:logback-android`). case 2 is correct, and you should stick with that.

To troubleshoot, enable debug output with `<configuration debug="true">` and cold-start the app (terminate beforehand if necessary). You should see `System.out` logging in logcat.

**Comment by haghpanah** [comment]
Oh, How come? I have it in my archiva repo
![untitled](https://cloud.githubusercontent.com/assets/4939854/16175239/167581de-35fb-11e6-8b00-ffe9ee691c91.png)
I'll test your suggestion and inform you as soon as I can
Thanks for your attention

**Comment by tony19** [comment]
Oh, so you're using your own repo instead of Maven Central. I suppose that would work, but it's confusing because you're effectively creating an unofficial group ID for `logback-android`. Out of curiosity, why are you doing that?

**Comment by haghpanah** [comment]
Again thanks for your attention,

In fact, the repo is not mine and it is a legacy corporate repo and I've just inherited from others,
I did as you suggested and still have no result (it is not logging) but `ch.qos.logback` does
I have attached a simple project structure that I've used for testing
If possible, please take look at it, maybe I've made something wrong
I also have attached the jar for the `logback-android` (from my the local repo) as well as its related POM
if you need something more please let me know,
I have to migrate to you library as I have problems with previous `ch.qos.logback` specifically when the final apk has been obfuscated
Regards,

[zz.tester.zip](https://github.com/tony19/logback-android/files/322108/zz.tester.zip)

[logback-android-1.0.6-1.zip](https://github.com/tony19/logback-android/files/322111/logback-android-1.0.6-1.zip)

**Comment by tony19** [comment]
I think I know what the problem is. In 1.0.8-1, `logback-android` no longer searches the `AndroidManifest.xml` by default (as an optimization). You either have to move the config into `assets/logback.xml` or setup your [initialization search path](https://github.com/tony19/logback-android/wiki#initialization-search-path) to read the config from the manfiest. I recommend using `assets/logback.xml` because it's faster than parsing the manifest.

**Comment by haghpanah** [comment]
Thanks for your kindly help,
I put the configuration file at `assets/logback.xml` and it is now working like a charm.
