### ISSUE TITLE
Reference to javax.mail.internet

### ISSUE THREAD

**Issue by MarcusWolschon** [tony19/logback-android#124]
Lint is complaining:

**logback-android-core-1.1.1-5.jar
InvalidPackage**
Priority: High
_Invalid package reference in library; not included in Android: `javax.mail.internet`.
Referenced from `ch.qos.logback.core.net.SMTPAppenderBase`._

**logback-android-core-1.1.1-5.jar
InvalidPackage**
Priority: High
_Invalid package reference in library; not included in Android: `javax.mail`.
Referenced from `ch.qos.logback.core.net.LoginAuthenticator`._

That package never exists on Android. This reference should not be there.
Can the
https://github.com/tony19/logback-android/blob/master/logback-core/src/main/java/ch/qos/logback/core/net/SMTPAppenderBase.java
even be used on Android?
It seems to be inherited from Logback but should be removed for logback-android.

**Comment by tony19** [comment]
To use the `SMTPAppender`, follow the [note from the Wiki](https://github.com/tony19/logback-android/wiki/Appender-Notes#smtpappender):

```
dependencies {
    compile 'com.sun.mail:android-mail:1.5.5'
    compile 'com.sun.mail:android-activation:1.5.5'
}
```

Also see [this](https://github.com/tony19/logback-android/wiki#proguard):

> If you don't use the mailing features of logback (i.e., the SMTPAppender), you might encounter an error while exporting your app with ProGuard. To resolve this, add the following rule:

>     -dontwarn ch.qos.logback.core.net.*
