### ISSUE TITLE
Proguard warning - references unknown class member

### ISSUE THREAD

**Issue by lirik16** [tony19/logback-android#125]
Hi @tony19. Thank you for the greate work!
I updated logback-android and slf4j-api to the latest versions that described in the readme file
> dependencies {
  compile 'org.slf4j:slf4j-api:1.7.21'
  compile 'com.github.tony19:logback-android-core:1.1.1-5'
  compile 'com.github.tony19:logback-android-classic:1.1.1-5'
}

and get a proguard error after the update
> org/slf4j/MDC.bwCompatibleGetMDCAdapterFromBinder:()Lorg/slf4j/spi/MDCAdapter; references unknown class member: org/slf4j/impl/StaticMDCBinder.getSingleton:()Lorg/slf4j/impl/StaticMDCBinder;
org/slf4j/MarkerFactory.bwCompatibleGetMarkerFactoryFromBinder:()Lorg/slf4j/IMarkerFactory; references unknown class member: org/slf4j/impl/StaticMarkerBinder.getSingleton:()Lorg/slf4j/impl/StaticMarkerBinder;

It looks like that we also need to include compile directive for slf4j-android. Something like this 
> compile 'org.slf4j:slf4j-android:1.7.21'

**Comment by tony19** [comment]
I can't reproduce this problem. The only errors I see are benign lint errors about `javax.mail`. Can you provide a working example to reproduce the problem?

**Comment by lirik16** [comment]
Sorry for the delay.
I created a repo with the example - https://github.com/lirik16/logback-android-proguard-test. You can reproduce the problem by executing `gradlew clean assembleDebug`. In my case I see this gradle output

> :clean UP-TO-DATE
:app:clean
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2411Library
:app:prepareComAndroidSupportAppcompatV72411Library
:app:prepareComAndroidSupportDesign2411Library
:app:prepareComAndroidSupportRecyclerviewV72411Library
:app:prepareComAndroidSupportSupportV42411Library
:app:prepareComAndroidSupportSupportVectorDrawable2411Library
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:mergeDebugShaders
:app:compileDebugShaders
:app:generateDebugAssets
:app:mergeDebugAssets
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources
:app:mergeDebugResources
:app:processDebugManifest
:app:processDebugResources
:app:generateDebugSources
:app:incrementalDebugJavaCompilationSafeguard
:app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources
:app:prePackageMarkerForDebug
:app:transformClassesWithNewClassShrinkerForDebug
org/slf4j/MarkerFactory.bwCompatibleGetMarkerFactoryFromBinder:()Lorg/slf4j/IMarkerFactory; references unknown class member: org/slf4j/impl/StaticMarkerBinder.getSingleton:()Lorg/slf4j/impl/StaticMarkerBinder;
org/slf4j/MDC.bwCompatibleGetMDCAdapterFromBinder:()Lorg/slf4j/spi/MDCAdapter; references unknown class member: org/slf4j/impl/StaticMDCBinder.getSingleton:()Lorg/slf4j/impl/StaticMDCBinder;
:app:transformClassesWithNewClassShrinkerForDebug FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformClassesWithNewClassShrinkerForDebug'.
> Warnings found during shrinking, please use -dontwarn or -ignorewarnings to suppress them.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 19.335 secs

**Comment by lirik16** [comment]
I also created a pr with small fix.

**Comment by tony19** [comment]
Please try [1.1.1-6](https://github.com/tony19/logback-android/releases/tag/v_1.1.1-6)

**Comment by lirik16** [comment]
It works. Thank you.
Problem fixed so I close the issue.
