### ISSUE TITLE
Configuring logger for android using AsyncAppender + FileAppender

### ISSUE THREAD

**Issue by AlexanderGarmash** [tony19/logback-android#129]
Hello.
I have problem with writing logs to file.
This is my configuration stuff:

```
        LoggerContext context = (LoggerContext) LoggerFactory.getILoggerFactory();
        context.reset();

        final String LOG_DIR = resolveLogFolder(externalStorageDirectory, appId);
        final String FILE_NAME = "/" + fileFormat.format(new Date()) + ".txt";

        // setup FileAppender
        PatternLayoutEncoder encoder1 = new PatternLayoutEncoder();
        encoder1.setContext(context);
        encoder1.setPattern("%d{HH:mm:ss.SSS} [%thread] %-5level %logger{35} - %msg%n");
        encoder1.start();

        FileAppender<ILoggingEvent> fileAppender = new FileAppender<ILoggingEvent>();
        fileAppender.setContext(context);
        fileAppender.setName(MY_LOGGER);
        fileAppender.setFile(LOG_DIR + FILE_NAME);
        fileAppender.setEncoder(encoder1);
        fileAppender.start();

        AsyncAppender asyncAppender = new AsyncAppender();
        asyncAppender.setContext(context);
        asyncAppender.setName("ASYNC");
        asyncAppender.setIncludeCallerData(false);
        asyncAppender.addAppender(fileAppender);
        asyncAppender.start();

        ch.qos.logback.classic.Logger root = (ch.qos.logback.classic.Logger) LoggerFactory.getLogger(MY_LOGGER);
        root.addAppender(fileAppender);

        StatusPrinter.print(context);
```

Then I obtain instance of logger:

```
log = LoggerFactory.getLogger(MY_LOGGER);
```

and provide this instance to everywhere using DI.

I log what I need using method `info`:

```
log.info(msg);
```

Then, when in my main activity's 'onDestroy' I stop logging:

```
LoggerContext loggerContext = (LoggerContext) LoggerFactory.getILoggerFactory();
        loggerContext.stop();
```

The problem is I have no any logs in my target dir. No one file. Can you please point me, what's wrong did I do?
# UPDATE

This is an error from logcat:
|-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [assets/logback.xml]
|-INFO in ch.qos.logback.core.FileAppender[MyLogger] - File property is set to [/myapp/com.mycopany.puppyslots/logs//2016-08-23_0554.txt]
|-ERROR in ch.qos.logback.core.FileAppender[MyLogger] - Failed to create parent directories for [/myapp/com.mycopany.puppyslots/logs/2016-08-23_0554.txt]
|-ERROR in ch.qos.logback.core.FileAppender[MyLogger] - openFile(/myapp/com.mycopany.puppyslots/logs//2016-08-23_0554.txt,true) failed java.io.FileNotFoundException: /myapp/com.mycopany.puppyslots/logs/2016-08-23_0554.txt: open failed: ENOENT (No such file or directory)

Thanks.

**Comment by tony19** [comment]
As indicated in your update, `logback-android` failed to create the parent directories of your target log file. It looks like your `resolveLogFolder()` is not returning the correct path. I would've expected at least a leading path of `/data/data/[...]`.

I'm considering the issue closed. Feel free to comment otherwise.
