### ISSUE TITLE
DATA DIR is not correct when inside an adroid profile

### ISSUE THREAD

**Issue by lgafniel** [tony19/logback-android#130]
When inside an android for work profile, data dir is at _/data/user/<user id>_ and not at _/data/data_ (which is actually linked with _/data/user/0_ - the default).

CommonPathUtil's methods assume the default user is running the app, which causes file appenders defined with ${DATA_DIR} to not work in this scenario.

**Comment by mgohin** [comment]
+1, I have this problem too, I have to use Java configuration :(

**Comment by tony19** [comment]
This should be fixed in 10d35f7. If interested, you can try the `1.1.1-11-SNAPSHOT`.

**Comment by mgohin** [comment]
Nice it works ! Any chance to get a release @tony19 please ?

**Comment by tony19** [comment]
Released in [v_1.1.1-11](https://github.com/tony19/logback-android/releases/tag/v_1.1.1-11)

**Comment by mgohin** [comment]
Got a new problem, it works on some devices but on others I got this : 
```
04-12 09:31:15.629 21508-21508/? I/System.out: 09:31:15,628 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[rotation] - openFile(/logs/myapp.log,true) failed java.io.FileNotFoundException: /logs/myapp.log: open failed: ENOENT (No such file or directory)
```

```xml
<appender name="rotation" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${DATA_DIR}/logs/myapp.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>${DATA_DIR}/logs/myapp.%d{yyyy-MM-dd}.log.zip</fileNamePattern>
            <timeBasedFileNamingAndTriggeringPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP">
                <maxFileSize>10MB</maxFileSize>
            </timeBasedFileNamingAndTriggeringPolicy>
            <maxHistory>2</maxHistory>
        </rollingPolicy>
        <encoder>
            <pattern>%date{dd MMM yyyy;HH:mm:ss.SSS} [%thread] %-5level %logger{35} - %msg%n</pattern>
        </encoder>
    </appender>
```

The device is on android 6.0.1.

Any idea ?

**Comment by mgohin** [comment]
Same on Android 8

**Comment by mgohin** [comment]
opened a new issue : https://github.com/tony19/logback-android/issues/172
