### ISSUE TITLE
Could not create an Appender of type [ch.qos.logback.core.FileAppender]. 

### ISSUE THREAD

**Issue by chasten** [tony19/logback-android#131]
Could not create an Appender of type [ch.qos.logback.core.FileAppender]. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.core.FileAppender

I found the exception only on OPPO phone, do you have any help?

**Comment by tony19** [comment]
@chasten I'm not familiar with ColorOS (Oppo's Android variant). Does this exception only occur on that phone (no others)? What's the full stacktrace?

**Comment by tony19** [comment]
I assume this issue is no longer relevant. Feel free to create a new issue if necessary.
