### ISSUE TITLE
Encrypt logs

### ISSUE THREAD

**Issue by gnuhel** [tony19/logback-android#133]
Hi @tony19 

is it possible to encrypt logs usind logback? I need to de/encrypt log files for logging.
Is it possible to integrate it into the FileAppender?

Thanks

**Comment by tony19** [comment]
While file encryption is an interesting feature, it's not one that `logback-android` supports out of the box (nor will it in the future). :) However, you could easily create your own appender (e.g., that extends FileAppender) to support encryption. Check out http://logback.qos.ch/manual/appenders.html#WriteYourOwnAppender
