### ISSUE TITLE
Size and time rolling not working

### ISSUE THREAD

**Issue by orikl84** [tony19/logback-android#138]
First, why SizeAndTimeBasedRollingPolicy is missing from android logback version 1.1.1-6?

Anyhow, I tried the following:

// setup FileAppender
        PatternLayoutEncoder encoder1 = new PatternLayoutEncoder();
        encoder1.setContext(lc);
        encoder1.setPattern("%d{yyyy-MM-dd/HH:mm:ss.SSS,GMT} [%thread] %-5level %logger{36} - %msg%n");
        encoder1.start();

        final String LOG_DIR = TechOwnerApp.getContext().getExternalFilesDir("logs").getAbsolutePath();

        RollingFileAppender<ILoggingEvent> fileAppender = new RollingFileAppender<>();
        fileAppender.setAppend(true);
        fileAppender.setContext(lc);
        fileAppender.setFile(LOG_DIR + "/app.log");

        Resources resources = TechOwnerApp.getContext().getResources();

        TimeBasedRollingPolicy<ILoggingEvent> rollingPolicy = new TimeBasedRollingPolicy<>();
        rollingPolicy.setFileNamePattern(LOG_DIR + "/log.%d.txt");
        rollingPolicy.setMaxHistory(resources.getInteger(R.integer.max_history));

        rollingPolicy.setParent(fileAppender);  // parent and context required!
        rollingPolicy.setContext(lc);
        rollingPolicy.start();

        SizeBasedTriggeringPolicy sizeBasedTriggeringPolicy = new SizeBasedTriggeringPolicy();
        sizeBasedTriggeringPolicy.setMaxFileSize("10KB");
        sizeBasedTriggeringPolicy.start();

        fileAppender.setRollingPolicy(rollingPolicy);
        fileAppender.setTriggeringPolicy(sizeBasedTriggeringPolicy);

        fileAppender.setEncoder(encoder1);
        fileAppender.start();

And its not working at all. No files are created at all.

Is there a way to add size limit to the file (or even to all of the files)

**Comment by hnxylc8818** [comment]
I had a similar problem with you, and finally I did:
```
private static void configureLogbackDirectly(String log_dir, String filePrefix) {
        LoggerContext context = (LoggerContext) LoggerFactory.getILoggerFactory();
        context.reset();


        RollingFileAppender<ILoggingEvent> rollingFileAppender = new RollingFileAppender<ILoggingEvent>();
        rollingFileAppender.setAppend(true);
        rollingFileAppender.setContext(context);

        TimeBasedRollingPolicy<ILoggingEvent> rollingPolicy = new TimeBasedRollingPolicy<ILoggingEvent>();
        rollingPolicy.setFileNamePattern(log_dir + "/" + filePrefix + "_%d{yyyyMMdd}.%i.log");
        rollingPolicy.setMaxHistory(7);
        rollingPolicy.setParent(rollingFileAppender);
        rollingPolicy.setContext(context);


        SizeAndTimeBasedFNATP<ILoggingEvent> sizeAndTimeBasedFNATP = new SizeAndTimeBasedFNATP<>();
        sizeAndTimeBasedFNATP.setMaxFileSize("1000KB");
        sizeAndTimeBasedFNATP.setContext(context);
        sizeAndTimeBasedFNATP.setTimeBasedRollingPolicy(rollingPolicy);

        rollingPolicy.setTimeBasedFileNamingAndTriggeringPolicy(sizeAndTimeBasedFNATP);
        rollingPolicy.start();
        sizeAndTimeBasedFNATP.start();
        rollingFileAppender.setRollingPolicy(rollingPolicy);

        PatternLayoutEncoder encoder = new PatternLayoutEncoder();
        encoder.setPattern("%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n");
        encoder.setContext(context);
        encoder.start();

        rollingFileAppender.setEncoder(encoder);
        rollingFileAppender.start();

        ch.qos.logback.classic.Logger root = (ch.qos.logback.classic.Logger) LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME);
        root.setLevel(Level.TRACE);
        root.addAppender(rollingFileAppender);
    }
```

**Comment by kumien** [comment]
How can I configure it from XML file?
