### ISSUE TITLE
1.1.1-6: Android Lint: "InvalidPackage" warnings

### ISSUE THREAD

**Issue by walles** [tony19/logback-android#140]
Hi!

Try this:
* `git clone https://github.com/walles/flickr-uploader.git`
* `cd flickr-uploader`
* `git checkout walles/logback-android-repro`
* `./gradlew lint`

Current result:
```
[...]
Ran lint on variant debug: 2 issues found
/Users/johan/.gradle/caches/modules-2/files-2.1/com.github.tony19/logback-android-core/1.1.1-6/93117015ae639e6482e4e1ad5f988c3f61d09fe0/logback-android-core-1.1.1-6.jar: Error: Invalid package reference in library; not included in Android: javax.mail.internet. Referenced from ch.qos.logback.core.net.SMTPAppenderBase. [InvalidPackage]
/Users/johan/.gradle/caches/modules-2/files-2.1/com.github.tony19/logback-android-core/1.1.1-6/93117015ae639e6482e4e1ad5f988c3f61d09fe0/logback-android-core-1.1.1-6.jar: Error: Invalid package reference in library; not included in Android: javax.mail. Referenced from ch.qos.logback.core.net.LoginAuthenticator. [InvalidPackage]

   Explanation for issues of type "InvalidPackage":
   This check scans through libraries looking for calls to APIs that are not
   included in Android.
[...]
```

Expected result:
* Lint should pass

**Comment by groys** [comment]
Having the same issue, after updating to Android Studio 2.3 with gradle plugin 2.3. The new version seems to include a stricter lint check. I have had to fix other lint issues across my project after upgrading

**Comment by groys** [comment]
Workaround is to add this to your lint.xml file

<lint>
    <issue id="InvalidPackage">
        
        <ignore regexp="javax.mail"/>
    </issue>
</lint>

**Comment by groys** [comment]
Workaround is to add this to your lint.xml file

`<lint>
    <issue id="InvalidPackage">
        
        <ignore regexp="javax.mail"/>
    </issue>
</lint>`

**Comment by tony19** [comment]
This is no longer an issue in [1.1.1-7](https://github.com/tony19/logback-android).
