### ISSUE TITLE
LogcatAppender doesn't show trace in root level "ALL"

### ISSUE THREAD

**Issue by JonasVautherin** [tony19/logback-android#141]
I have a logcat appender (`ch.qos.logback.classic.android.LogcatAppender`) set up with root level "ALL", like so:

    <root level="ALL">
        <appender-ref ref="logcat" />
    </root>

Logcat is showing all the other log messages (debug, error, info, etc.) but not the trace log messages. I would expect them to be outputted as "Verbose". Am I wrong?

**Comment by JonasVautherin** [comment]
Adding tests in `LogcatAppenderTest` and running them with

    ./gradlew test --tests ch.qos.logback.classic.android.LogcatAppenderTest

I believe I can confirm it is a bug

**Comment by JonasVautherin** [comment]
I just realized that `LogcatAppenderTest` actually runs `context.reset();` in `@before`, which resets the debug level to "DEBUG". That doesn't actually test my initial problem =/.

**Comment by tony19** [comment]
@JonasVautherin I cannot reproduce this. Can you share a sample GitHub project?

**Comment by JonasVautherin** [comment]
Hmm, I apparently had something wrong in my `logback.xml`. I had a second logger defined that was actually not declared (and somehow I thought this second one was working), something like:

```
<root level="ALL">
    <appender-ref ref="logcat" />
</root>
<root level="ALL">
    <appender-ref ref="something_weird" />
</root>
```

More than preventing the trace of "logcat" to work, it was then doubling the debug of it. Interesting behavior... :-)

Thanks a lot for your help!

**Comment by JonasVautherin** [comment]
Wait, actually the second one, i.e. "something_weird", was set to "DEBUG". So defining root level for an undefined logger apparently has an effect on other ones.

**Comment by tony19** [comment]
@JonasVautherin It sounds like it could be a bug. Yes, please create a repro for it. Thanks!
