### ISSUE TITLE
this can't be used to Android Studio 3.0 beta

### ISSUE THREAD

**Issue by acaixuediananao** [tony19/logback-android#144]
I want to change my project to kotlin . So , I open my project with AS 3.0 beta  . when i sync my project ,there is an error :

Error:Failed to resolve: com.google.android:android:2
when i remove this ,is built success!
i don't know why
please help me ! thank you!

**Comment by stari4ek** [comment]
Exclude dependency:
```
    compile ('com.github.tony19:logback-android-classic:1.1.1-6') {
        exclude group: 'com.google.android'
    }
```

**Comment by nbhuzan** [comment]
查了好长时间，才查到是这里的问题，上来一看，原来这里已经有答案了

**Comment by tony19** [comment]
This should no longer be required in [1.1.1-7](https://github.com/tony19/logback-android/releases/tag/v_1.1.1-7).
