### ISSUE TITLE
Gradle Plugin 3.0.0 cannot find symbol

### ISSUE THREAD

**Issue by pentarex** [tony19/logback-android#153]
Hi I am using your library, kotlin, dagger2, realm and kapt

After upgrading to gradle plugin 3.0.0 Ive started receiving exceptions from the autogenerated classes from kapt like

```bash
/project/ABP/app/build/generated/source/kapt/debug/io/realm/CommMetaDataRealmProxy.java:276: error: cannot find symbol
e: 

e:     @TargetApi(Build.VERSION_CODES.HONEYCOMB)
```

It took me around a day to find the error and reproduce it, it was from the library com.github.tony19:logback-android-classic:1.1.1-6 and for some reason ive added it without the workaround for issue #73 in my build.gradle, now adding it, solved my issue. Just wanted to post it here so if someone else had the same issue can appear in google :) 

You can mark it as solved and closed if you want

**Comment by tony19** [comment]
This should no longer be required in [1.1.1-7](https://github.com/tony19/logback-android/releases/tag/v_1.1.1-7).
