### ISSUE TITLE
android 4.4.2   NoClassDefFoundError

### ISSUE THREAD

**Issue by njzy63lys** [tony19/logback-android#156]
java.lang.NoClassDefFoundError: ch.qos.logback.core.rolling.RollingFileAppender 
I'm relying on it. I uninstall APK and then install it.   I think it could be the lib conflict. Because I used org.apache.commons . Please tell me about bug.  How to  do?   THX

**Comment by njzy63lys** [comment]
I've solved this problem. 
thk

**Comment by mgohin** [comment]
Can you provide your solution @njzy63lys please ? I've got a similar case

**Comment by njzy63lys** [comment]
http://www.jianshu.com/p/8b4f711da0bb     @mgohin      You try it

**Comment by tony19** [comment]
If this is still an issue, please feel free to comment with steps to reproduce. (I wasn't able to reproduce it myself).
