### ISSUE TITLE
Please add information on how to exclude xmlpullparser to your wiki

### ISSUE THREAD

**Issue by OneWorld123** [tony19/logback-android#160]
Please change in your wiki section "download"

`compile('com.github.tony19:logback-android-classic:1.1.1-6')`

to 

```
compile('com.github.tony19:logback-android-classic:1.1.1-6') {
   exclude group: 'xpp3', module: 'xpp3'//exclude XmlPullParser in order to avoid "Multiple dex files define" errors
}
```

Users not too familiar in excluding things in gradle will thank you!

Whole background: https://stackoverflow.com/questions/47335142/android-gradle-plugin-3-0-0-multiple-dex-files-define-lorg-xmlpull-mxp1-mxparse/48560428#48560428

**Comment by tony19** [comment]
This is no longer required in [1.1.1-7](https://github.com/tony19/logback-android/releases/tag/v_1.1.1-7).
