### ISSUE TITLE
Could not resolve com.github.tony19:logback-android-core:1.1.1-6

### ISSUE THREAD

**Issue by christocracy** [tony19/logback-android#161]
I'm seeing a number of reports of failing to retrieve `logback` dependencies:

```
 > Could not resolve com.github.tony19:logback-android-core:1.1.1-6.
               > Could not get resource 'https://jitpack.io/com/github/tony19/logback-android-core/1.1.1-6/logback-android-core-1.1.1-6.pom'.
                  > Could not GET 'https://jitpack.io/com/github/tony19/logback-android-core/1.1.1-6/logback-android-core-1.1.1-6.pom'. Received status code 401 from server: Unauthorized

> Could not resolve com.github.tony19:logback-android-classic:1.1.1-6.
               > Could not get resource 'https://jitpack.io/com/github/tony19/logback-android-classic/1.1.1-6/logback-android-classic-1.1.1-6.pom'.
                  > Could not GET 'https://jitpack.io/com/github/tony19/logback-android-classic/1.1.1-6/logback-android-classic-1.1.1-6.pom'. Received status code 401 from server: Unauthorized

```

Is this returning `401` for you?

https://jitpack.io/com/github/tony19/logback-android-classic/1.1.1-6/logback-android-classic-1.1.1-6.pom'

**Comment by tony19** [comment]
Yes, I see the `401` too. The issue seems to be on Jitpack's side. The docs say Jitpack should only require credentials for private repos (which this repo is not), so I don't know what the cause is. I've even tried creating an account and authorizing the Jitpack app. I've reached out to them on Gitter (perhaps you should too for a faster response).

**Comment by christocracy** [comment]
Yea, clearly something weird with Jitpack.  I’ve never had an issue personally, just some customers.

However, I think it’s related to order of repository urls (eg jitback before jCenter) in addition to build-failures from unrelated issue.
