### ISSUE TITLE
Can't get newline to work

### ISSUE THREAD

**Issue by aloh86** [tony19/logback-android#162]
I can't get newlines to work when writing to file. It always gets written in a single line. I have tried both:

`%date{"dd MMM yyyy, HH:mm:ss"} %level [%thread] %class{0}: %message%n`
and
`%m%n`

Am I misunderstanding how %n works? Here is the full appender:

`<appender name="file" class="ch.qos.logback.core.FileAppender"
    <file>${LOG_DIR}/apparent.log</file>
        <encoder>
            <pattern>%date{"dd MMM yyyy, HH:mm:ss"} %level [%thread] %class{0}: %message%n</pattern>
        </encoder>
</appender>`

**Comment by tony19** [comment]
I cannot reproduce this. That pattern works for me. What version of `slf4j-api` and `logback-android` are you using?

**Comment by aloh86** [comment]
I am using:

- org.slf4j:slf4j-api:1.7.21
- com.github.tony19:logback-android:1.1.1-8

**Comment by aloh86** [comment]
Hm, actually tony19, it looks like it is creating the newlines. When I open it in Wordpad, Visual Studio Code, Microsoft Word, each log message is on it's own line. However, when it is opened in Notepad, all the text is on a single line.

Any ideas why Notepad is not handling the newlines?

**Comment by aloh86** [comment]
I think it's for the reason's described here. https://superuser.com/questions/362087/notepad-ignoring-linebreaks
