### ISSUE TITLE
License Change

### ISSUE THREAD

**Issue by deka91** [tony19/logback-android#164]
When will be the next major release with the license change?

**Comment by tony19** [comment]
Within the next 3 months (tentatively).

**Comment by WillEllis** [comment]
Is this going to happen? I'd be interested

**Comment by tony19** [comment]
Yes, it's definitely happening. I plan on a major version bump to 2.0.0.

**Comment by WillEllis** [comment]
Great to hear, any ideas on a rough release date?  The previous comment was "within 3 months" but 12 months ago. Cheers for the great library!

**Comment by tony19** [comment]
This week. It'll be [Apache 2.0](http://www.apache.org/licenses/LICENSE-2.0).

**Comment by tony19** [comment]
Fixed in [2.0.0](https://github.com/tony19/logback-android/releases/tag/v_2.0.0)
