### ISSUE TITLE
TimeBasedRollingPolicy not working in Android 8.1

### ISSUE THREAD

**Issue by jorgedfi** [tony19/logback-android#165]
Hi, 

It seems that the RollingFileAppender stopped creating new files on Android 8.1 

Both the trigger and the rolling policy are not working

```
<configuration>

    <property name="LOG_DIR" value="/data/data/com.dallas.trolley.debug/files/log" />

    <appender name="file" class="ch.qos.logback.core.rolling.RollingFileAppender" debug='true'>
        <file>${LOG_DIR}/local_logs.txt</file>

        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>${LOG_DIR}/local_logs.%d.txt</fileNamePattern>
            <maxHistory>2</maxHistory>
        </rollingPolicy>

        <triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
            <maxFileSize>50KB</maxFileSize>
        </triggeringPolicy>

        <encoder>
            <pattern>%d{yyyy/MM/dd HH:mm:ss:SSS} [%thread] %-1level %logger{36} - %msg%n</pattern>
        </encoder>

    </appender>

    <root level="INFO">
        <appender-ref ref="file" />
    </root>

</configuration>
```

Thanks!

**Comment by tony19** [comment]
I see a typo in `rollingPolicy > fileNamePattern` (`{LOG_DIR}` instead of `${LOG_DIR}`). Is that the cause of the problem?

**Comment by jorgedfi** [comment]
My bad, (edited with the typo fix). However, I still have the same issue. I really appreciate the help :). 

Interestingly using an emulator with an OS version lower than Android Oreo makes it work

**Comment by tony19** [comment]
The problem here is similar to #203. I recommend switching to `SizeAndTimeBasedRollingPolicy`.

> Using `TimeBasedRollingPolicy` and `SizeBasedTriggeringPolicy` results in an exception similar to the one seen in [LOGBACK-995](https://jira.qos.ch/browse/LOGBACK-995). Instead, use [`SizeAndTimeBasedRollingPolicy`](https://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedRollingPolicy) for the rolling policy. Note that it also serves as a triggering policy, so you don't need to add one.
