### ISSUE TITLE
Multiple Discriminator for Sifiting Appender

### ISSUE THREAD

**Issue by 51M0Ng** [tony19/logback-android#166]
Hi Tony,

I am writing the log with Sifting Appender, that it would able to get the logger name as a file name,
Then it is implemented successfully. But I got another problem with TimeBasedRolling, then I give up on it.

Code for Time-based Rolling inside the Sifting Appender
```
<appender name="SIFT" class="ch.qos.logback.classic.sift.SiftingAppender">
  <discriminator class="com.mlp.multimedialayoutplayer.LoggerNameBasedDiscriminator" />
    <sift>
      <appender name="FILE-${loggerName}" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${LOGDIR}/${loggerName}.log</file>

	<rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
	  <fileNamePattern>${LOGDIR}/%d/${loggerName}.log</fileNamePattern>
          <maxHistory>30</maxHistory> 
	</rollingPolicy>	
	
        <encoder>
            <charset>UTF-8</charset>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS}|[%thread]|%-5level|%class{36}.%M:%L|%msg%n</pattern>
        </encoder>
      </appender>
    </sift>
</appender>
```

Then I tried to add two "discriminator" tags to obtains two values from the custom discriminator class, I do a lot of study from the internet, it looks like the SIFT doesn't support multiple "discriminator" tags. But information is not enough for this issues,  **I just want to ask for is it possible to implement multiple "discriminator" tags?** (I can obtain one of the value, another one would show as an UNDEFINED)

**Comment by tony19** [comment]
> Is it possible to using Time Based Rolling Policy inside the Sifting Appender?

Yes. If the rollover isn't occurring, it's either a bug in `logback-android` or misconfiguration. I recommend verifying that the configuration for the `RollingFileAppender` works outside the `SiftingAppender`, and then trying it inside the `SiftingAppender`. Make sure to enable debug in your `logback` configuration to troubleshoot the rollover. If you determine it's a bug in `RollingFileAppender`, please create an issue with the relevant details to reproduce the issue (a sample GitHub project would be ideal).

> I just want to ask for is it possible to implement multiple "discriminator" tags?

No, the `SiftingAppender` can only accept one discriminator.
