### ISSUE TITLE
SQLiteAppender stackTrace lines contains ~[na:0.0]

### ISSUE THREAD

**Issue by mauron85** [tony19/logback-android#171]
First, I want to thank you for this amazing logger.

I'm only having small issue when trying to retrieve stack trace stored by SQLiteAppender:

```
java.lang.IllegalStateException: DAEMON HAS BEEN RELEASED! WELCOME TO HELL!
at com.marianhello.bgloc.LocationService.configure(LocationService.java:365) ~[na:0.0]
at com.marianhello.bgloc.LocationService.access$200(LocationService.java:60) ~[na:0.0]
at com.marianhello.bgloc.LocationService$IncomingHandler.handleMessage(LocationService.java:174) ~[na:0.0]
at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
at android.os.Looper.loop(Looper.java:136) ~[na:0.0]
at android.app.ActivityThread.main(ActivityThread.java:5001) ~[na:0.0]
at java.lang.reflect.Method.invokeNative(Native Method) ~[na:0.0]
at java.lang.reflect.Method.invoke(Method.java:515) ~[na:0.0]
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) ~[na:0.0]
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) ~[na:0.0]
at dalvik.system.NativeStart.main(Native Method) ~[na:0.0]
```

All stack trace lines seems to be stored in sqlite row with suffix `~[na:0.0]`. Wondering what it is and if possible how to strip before joining those lines.

**Comment by tony19** [comment]
That's supposed to be class packaging information. Here's the excerpt from the [logback manual](https://logback.qos.ch/manual/layouts.html#xThrowable):

> At the end of each stack frame of the exception, a string consisting of the jar file containing the relevant class followed by the "Implementation-Version" as found in that jar's manifest will be added. This innovative technique was originally suggested by James Strachan. If the information is uncertain, then the class packaging data will be preceded by a tilde, i.e. the '~' character.
>
> Here is an example:
>
>     java.lang.NullPointerException
>       at com.xyz.Wombat(Wombat.java:57) ~[wombat-1.3.jar:1.3]
>       at  com.xyz.Wombat(Wombat.java:76) ~[wombat-1.3.jar:1.3]
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.5.0_06]
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.5.0_06]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.5.0_06]
>       at java.lang.reflect.Method.invoke(Method.java:585) ~[na:1.5.0_06]
>       at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:59) [junit-4.4.jar:na]
>       at org.junit.internal.runners.MethodRoadie.runTestMethod(MethodRoadie.java:98) [junit-4.4.jar:na]
>       ...etc 

You can disable packaging data globally with:

```java
LoggerContext lc = (LoggerContext) LoggerFactory.getILoggerFactory();
lc.setPackagingDataEnabled(false);
```

In `logback` 1.1.4, this is disabled by default to improve performance, given how expensive the package data calculation is. This is planned for `logback-android` 1.1.4, but this feature is potentially on the chopping block to reduce the size of the library.

**Comment by mauron85** [comment]
Thank you for quick response and exhausting explanation. Normally I won't mind having this extra information, but in above scenario I'm using logback in default [UncaughtExceptionHandler](https://github.com/mauron85/background-geolocation-android/blob/master/src/main/java/com/marianhello/logging/UncaughtExceptionLogger.java) and output is different from users are used to see when their app crash.

Will try to disable this packaging data and then will close this issue.

**Comment by mauron85** [comment]
Disabling packaging data did the job! Thanks @tony19!
