### ISSUE TITLE
How exactly does the SQLiteAppender work?

### ISSUE THREAD

**Issue by deostroll** [tony19/logback-android#174]
Does it create tables automatically? Can I use greenDao ORM to query these tables? Where are the docs for this component?

**Comment by tony19** [comment]
Yes, the tables are created automatically by `SQLiteAppender`. It works similarly to [`DBNameAppender`](https://logback.qos.ch/manual/appenders.html#DBAppender).

I added [docs for `SQLiteAppender`](https://github.com/tony19/logback-android/wiki/Appender-Notes#sqliteappender). Hopefully that helps!
