### ISSUE TITLE
SQLiteAppender and ProGuard

### ISSUE THREAD

**Issue by dmazzoni** [tony19/logback-android#179]
### Issue description

In release builds obfuscated with ProGuard, logging to an SQLiteAppender results in the SQLite database file being created, but no entries are added to it. When ProGuard is disabled logging works as expected.

### Logback configuration

The logback configuration is carried out at runtime, without using the _logback.xml_ file. An `SQLiteAppender` and a `LogcatAppender` are started and added to the created loggers. The Logcat appender works in both obfuscated and unobfuscated builds, while the SQLite one does not append any entry to the database when using obfuscated builds.

### ProGuard rules

The relevant rules in our ProGuard file are:

```
-keep class org.slf4j.** { *; }
-keep class ch.qos.logback.** { *; }
-keepattributes *Annotation*
```

We have also tried adding the _public_ modifier after the `-keep` directive, but to no avail.
Is there any additional SQLite-related rule that we should add?

### Environment

**Library version**: `com.github.tony19:logback-android:1.1.1-11` + `org.slf4j:slf4j-api:1.7.25`
**Android version**: tested on Android 6.0.1 (LG Nexus 5) and 8.1.0 (Google Pixel 2)

**Comment by tony19** [comment]
Fixed in [`v_1.1.1-12`](https://github.com/tony19/logback-android/releases/tag/v_1.1.1-12)
