### ISSUE TITLE
Slack appender

### ISSUE THREAD

**Issue by pesekl** [tony19/logback-android#185]
Hi Tony,
Is it possible to use something like this? https://github.com/maricn/logback-slack-appender
When I add dependence to project with lockback-android I receive this error: "Multiple dex files define Lch/qos/logback/classic/pattern/PropertyConverter;"
Or does is exist different way to report to Slack?

**Comment by tony19** [comment]
Since that depends on `ch.qos.logback`, you'd have to exclude it in your config (`pom.xml`, `build.gradle`, etc.). Let me know how it goes

**Comment by pesekl** [comment]
This work for me, thx Tony
    api ('com.github.maricn:logback-slack-appender:1.4.0'){
        exclude module: 'logback-classic'
    }
