### ISSUE TITLE
minSdkVersion 15

### ISSUE THREAD

**Issue by nathan-prat** [tony19/logback-android#186]
Hello,

Since the migration to gradle, minSdkVersion has been set to 15, but the README still says it supports Android 2.1.
Could either update the README to say sdk 15 is the new minimum, or fix minSdkVersion to be compatible with the intended version?

PS: minSdkVersion was set around Feb 3, in commit adbd07005be, "Add Gradle scripts for subproject".

**Comment by tony19** [comment]
The min SDK version is now `9`. Released in [`1.1.1-13`](https://github.com/tony19/logback-android/releases/tag/v_1.1.1-13)
