### ISSUE TITLE
Logback doesn't work from inner class

### ISSUE THREAD

**Issue by vasyl91** [tony19/logback-android#188]
I can't run logback when it's in inner class, while from outer class it works like a charm. Is there any way to fix it?

```
//outer class
public class ClassifierModule extends ReactContextBaseJavaModule implements BufferListener {

    public ClassifierModule(ReactApplicationContext reactContext) {
        super(reactContext);
        appState = ((MainApplication)reactContext.getApplicationContext());
        }     

    @Override
    public String getName() {
      return "Classifier";
    }

    @ReactMethod
    public void saveLog() {
       logger.info("Hello world");
    }

    //inner class        
    public class ClassifierRunnable implements Runnable {

        public ClassifierRunnable(double[][] buffer) {
            rawBuffer = buffer;
            PSD = new double[NUM_CHANNELS][nbBins];
        }

        private final Logger logger = LoggerFactory.getLogger(ClassifierRunnable.class);

        @Override
        public void run() {
            if(isLogging) {

                int a = 11;
                int b = 24;

                logger.info(a)

            }
    }
}
```

**Comment by tony19** [comment]
Can you be more specific? What error/behavior are you seeing?

**Comment by vasyl91** [comment]
When I implement it in outer class .log file is being created while app installs and when I execute logger with button it appends lines to .log file. When I implement it in inner class totally nothing happens.. App doesn't create .log file and button does nothing. I receive no errors.

**Comment by tony19** [comment]
I'm not sure I follow your example. The `logger` is a private field inside the inner class, yet the outer class uses it in its own function. Can you provide a more complete example?

Btw, I just tried using a logger from an inner class, and it worked as expected (wrote logs to configured file).

**Comment by vasyl91** [comment]
Hmm, then I don't know what is going on. The app I'm modifying is based on react native and uses java as modules so I presume that it's because of it. 

Anyway I found a solution for this by sending event from inner class and listening it and saving with logback in outer one. For anyone having similar case -> https://stackoverflow.com/questions/52283050/how-to-intercept-event-in-java

Thank you for your help ;) I think that you can close this issue.
