### ISSUE TITLE
Can't change the default debug level to trace

### ISSUE THREAD

**Issue by lisong15** [tony19/logback-android#189]
at root property add level="trace",but still print info and heigher level log.this qus concern me for times;
add level="warn",then print right level.
please help me out

**Comment by tony19** [comment]
`TRACE` is equivalent to [`android.log.util.Log.VERBOSE`](https://developer.android.com/reference/android/util/Log.html#VERBOSE), which has higher verbosity than `DEBUG`. It sounds like you've already determined that `WARN` is the log level you need.

**Comment by lisong15** [comment]
> `TRACE` is equivalent to [`android.util.Log.VERBOSE`](https://developer.android.com/reference/android/util/Log.html#VERBOSE), which has higher verbosity than `DEBUG`, so it's correct for `INFO`-level and higher messages to still appear in the log. It sounds like you've already determined that `WARN` is the log level you need.

so the level value trace and debug is unabled anymore? the mininum level is info?

**Comment by tony19** [comment]
I don't understand your question.
