### ISSUE TITLE
If log data greater than 4K, The logcat display is incomplete

### ISSUE THREAD

**Issue by layox2008** [tony19/logback-android#194]
How to deal it?

**Comment by tony19** [comment]
Please provide reproduction steps.

**Comment by tony19** [comment]
Android itself has a fixed buffer length (4K characters) for each log entry (see [[1]](https://stackoverflow.com/q/8888654/6277151)), and `logback-android` does not try to workaround that. If you want to capture log entries longer than 4K characters, you could create a custom appender to break up the message.
