### ISSUE TITLE
Language change on device causes incorrect formatting

### ISSUE THREAD

**Issue by ergindogan** [tony19/logback-android#195]
Hi,

We are experiencing some issue with log formatting with our certain users. After digging into user's who are experiencing the issue I noticed that when user's change their language from English to other languages (for us it was Spanish, Russian, Turkish and Arabic) log formatting changes.

Our normal formatting (with language as English) is : 
`Jan 31 15:58:54 android-dev 12929231312:  (INFO | 1.0.0) [MainActivity] Sending token to server... `
but when we change language to Turkish log changes to :
`Jan 31 15:58:54 174.210.18.67 logger:  <14>Oca 31 15:58:54 android-dev 12929231312: (INFO | 1.0.0) [MainActivity] Sending token to server... `

There are two problems here. First is somehow `Jan 31 15:58:54 174.210.18.67 logger:` gets appended to the front. Second is that the actual date is getting formatted according to language on the second log(which is something I can fix easily).

Also important to note that I am sending my logs to papertrail.

Here is how I am using the lib :

**build.gradle**
```
implementation 'org.slf4j:slf4j-api:1.7.25'
implementation 'com.github.tony19:logback-android:1.3.0-2'
implementation('com.papertrailapp:logback-syslog4j:1.0.0') {
    exclude group: 'ch.qos.logback'
}
```

**logback.xml**
```
<configuration debug="true">
    <appender name="PAPERTRAIL" class="com.papertrailapp.logback.Syslog4jAppender">
        <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="com.comp.utils.other.MyAndroidPapertrailLayout" />
        </encoder>

        <syslogConfig class="org.productivity.java.syslog4j.impl.net.tcp.ssl.SSLTCPNetSyslogConfig">
            <host>MY_HOST</host>
            <port>MY_PORT</port>
            <facility>USER</facility>
            <sendLocalName>false</sendLocalName>
            <sendLocalTimestamp>false</sendLocalTimestamp>
            <maxMessageLength>128000</maxMessageLength>
        </syslogConfig>


        <!-- use lazy initialization so that network connection is not opened until first write -->
        <lazy>true</lazy>
    </appender>

    <appender name="ASYNC" class="ch.qos.logback.classic.AsyncAppender">
        <appender-ref ref="PAPERTRAIL" />
    </appender>

    <root level="DEBUG">
        <appender-ref ref="ASYNC" />
    </root>

</configuration>
```

**loggin code**
```
import ch.qos.logback.classic.spi.ILoggingEvent
import ch.qos.logback.core.LayoutBase
import com.comp.BuildConfig
import com.comp.data.dao.ProfileDao
import io.realm.Realm
import org.joda.time.DateTime

class MyAndroidPapertrailLayout : LayoutBase<ILoggingEvent>() {

    override fun doLayout(event: ILoggingEvent): String {
        val realm = Realm.getDefaultInstance()
        val profileDao = ProfileDao(realm)

        val text = if (profileDao.isThereAnyLoggedInProfiles()) {
            val profileId = profileDao.getActiveProfile().id
            "${DateTime(event.timeStamp).toString("MMM dd HH:mm:ss")} android-${if (BuildConfig.DEBUG) "dev" else "prod"} $profileId: (${event.level.levelStr} | ${BuildConfig.VERSION_NAME}) ${event.formattedMessage} "
        } else {
            "${DateTime(event.timeStamp).toString("MMM dd HH:mm:ss")} android-${if (BuildConfig.DEBUG) "dev" else "prod"} NOT_LOGGED_IN: (${event.level.levelStr} | ${BuildConfig.VERSION_NAME}) ${event.formattedMessage} "
        }

        realm.close()

        return text
    }
}
```

**calling the function**
```
val papertrailLogger: Logger = LoggerFactory.getLogger(MyActivity::class.java)
papertrailLogger.error("Hey it is me!")
```

How can I prevent incorrect log formatting? I don't want user's IP addresses to appear in the logs. I want to keep formatting like it is in English language.

Thanks!

**Comment by tony19** [comment]
Can you create a sample GitHub repo that reproduces the issue?

**Comment by ergindogan** [comment]
Hey, thank you for the response. I created a sample repo, you can find it [here](https://github.com/ergindogan/papertrailTest). 

Here are the logs:
<img width="722" alt="screen shot 2019-02-04 at 12 43 23 pm" src="https://user-images.githubusercontent.com/4639141/52236002-812f6980-287a-11e9-9128-5d64d4923fc7.png">

First line is when device is set to English and second line is when device is set to Turkish.

FYI : in the lockback.xml, you need to change host and port to your settings. They are currently placeholders.

**Comment by tony19** [comment]
I stepped through the code, and determined this is not a `logback-android` bug. The log event reaches the papertrail appender, which formats the event into a syslog message to send to the log server, which appears to be reformatting the received data.

The prefix seen that contains the hostname/IP is automatically inserted (by the server). You can confirm this by sending syslog messages from the command line (follow papertrail's [troubleshooting instructions](https://help.papertrailapp.com/kb/configuration/troubleshooting-remote-syslog-reachability/#use-remote_syslog2)).

**Comment by ergindogan** [comment]
Thank you for your response. I was shoot an email to papertrail in the meantime and got a response from them, indeed the log sent to papertrail should be in a specific format, that was the issue.

Response from papertrail :

> When Papertrail receives an RFC-compliant message, including a full syslog header, it parses out the sender name and program name from the provided header. When Papertrail receives a message that it can't parse, it interprets the entire thing as the message body, providing its own syslog header. So with these messages, the <14> signals the start of what Papertrail actually received, and the issue is that the month name is Oca instead of Jan, which is required by RFC 3164.
> Given that layout class, let's focus on the DateTime.toString method. That takes an optional second argument, locale. Passing Locale.US or Locale.ROOT in there ought to solve the problem. Mind giving that a shot?

Upon his message replacing `${DateTime(event.timeStamp).toString("MMM dd HH:mm:ss")}` with `${DateTime(event.timeStamp).withZone(DateTimeZone.forID("US/Pacific")).toString("MMM dd HH:mm:ss", Locale.US)}` solved my problem.

Hope this helps others who has the same issue.
