### ISSUE TITLE
variable ${PACKAGE_NAME} stopped working

### ISSUE THREAD

**Issue by mores** [tony19/logback-android#196]
Within logback.xml I have been using:
`<property` name="LOG_DIR" value="${EXT_DIR:-/sdcard}/Android/data/${PACKAGE_NAME}/files" />`

This works fine on versions:
com.github.tony19:logback-android-core:1.1.1-6
com.github.tony19:logback-android:1.1.1-8
com.github.tony19:logback-android:1.1.1-9

1.1.1-10 - ${PACKAGE_NAME} evaluated to  PACKAGE_NAME_IS_UNDEFINED

1.1.1-11 and every version higher: ${PACKAGE_NAME} is now an empty string

**Comment by tony19** [comment]
I'm guessing you've statically initialized your logger. You can resolve the issue by moving the init into `onCreate()`. See [note](https://github.com/tony19/logback-android/wiki#special-properties-for-xml-config).

**Comment by mores** [comment]
That was indeed the fix. Thanks for your time.
