### ISSUE TITLE
Daily rollover simply not work

### ISSUE THREAD

**Issue by yabee5566** [tony19/logback-android#198]
All daily rollover just simply don't work. It would rollover at other timing that is not on 00:00:00. I waste a lot of time here but failed.

**Comment by tony19** [comment]
The rollover would not automatically occur at midnight without a log event. This is documented in the notes [here](https://github.com/tony19/logback-android/wiki/Appender-Notes#fileappender-rollingfileappender):

> For rolling files, the file is rolled upon a log event past the rollover period (not automatically on time). This means that if no log events occur after 23 hours 59 minutes for a daily rollover period, the log file is not rolled over.

For example, if the app started at 11pm, and the next log event occurred at 2am, the log file would rollover at 2am. If you want the file to rollover at midnight, you'd have to log something at that time.

**Comment by yabee5566** [comment]
Sorry, I already did it and it just not work. I had tried TimeBasedRollingPolicy, SizeAndTimeBasedRollingPolicy. The rollover may happen in 8:00 or 10:00 something, just not at 00:00. The file for example, 2019-06-04.log would contains log in 2019-06-05.

**Comment by tony19** [comment]
Please provide reproduction steps, including the logback configuration (as prescribed in the bug report template).
