### ISSUE TITLE
Using logback-android with sentry-logback fails with duplicate class errors

### ISSUE THREAD

**Issue by vhermecz** [tony19/logback-android#199]
## Description

Tried to setup logging like: SLF4J -> Logback -> (Sentry & LogCat)

However, when I compile my project, I get a lot of duplicate class error like:
Duplicate class ch.qos.logback.classic.AsyncAppender found in modules classes.jar (com.github.tony19:logback-android:2.0.0) and logback-classic-1.2.1.jar (ch.qos.logback:logback-classic:1.2.1)

Looking into gradle app:dependencies I realized that while sentry-logback imports the logback libs (classic, core), this library actually contains the code for them.

## Steps to reproduce
Gradle build file is like:
```
dependencies {
    implementation 'org.slf4j:slf4j-api:1.7.26'
    implementation 'com.github.tony19:logback-android:2.0.0'
    implementation 'io.sentry:sentry-android:1.7.22'
    implementation 'io.sentry:sentry-logback:1.7.22'
}
```

## Environment

* **`logback-android` version:** 2.0.0
* **Android version:** NA (Used 7.0, API level 24)
* **Platform:** NA

**Comment by vhermecz** [comment]
Contents of src/main/assets/logback.xml

```xml
<configuration>
    <appender name="logcat" class="ch.qos.logback.classic.android.LogcatAppender">
        <tagEncoder>
            <pattern>%logger{12}</pattern>
        </tagEncoder>
        <encoder>
            <pattern>[%-20thread] %msg</pattern>
        </encoder>
    </appender>
    <appender name="sentry" class="io.sentry.logback.SentryAppender">
        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>WARN</level>
        </filter>
    </appender>
    <root level="DEBUG">
        <appender-ref ref="logcat" />
        <appender-ref ref="sentry" />
    </root>
</configuration>
```

**Comment by vhermecz** [comment]
Is it possible to move logback files to actual dependencies, or they are tweaked to the point where this would be infeasible? Thanks.

**Comment by tony19** [comment]
I'm not sure what you mean by *"moving the logback files to actual dependencies"*. You can avoid the build error by [excluding](https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:excluding_transitive_module_dependencies) `logback-classic` and `logback-core` from the `io.sentry:sentry-logback` dependency.
