### ISSUE TITLE
NPE: When manually calling RollingFileAppender.rollover()

### ISSUE THREAD

**Issue by ravsingh-inzura** [tony19/logback-android#206]
## Description

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.lastIndexOf(int)' on a null object reference
        at ch.qos.logback.core.rolling.helper.FileFilterUtil.afterLastSlash(Unknown Source:2)
        at ch.qos.logback.core.rolling.TimeBasedRollingPolicy.rollover(Unknown Source:6)

## Steps to reproduce

Programmatic configuration below.

Simply trying to call rollingFileAppender.rollover()
to trigger a rollover and be able to upload all available (daily) log files to our backend server.
After which i would like to delete old logs that are successfully uploaded.
Perhaps this is not the best way to achieve this?

    private void configureLogger(String logDirectory) {
        // reset the default context (which may already have been initialized)
        // since we want to reconfigure it
        LoggerContext loggerContext = (LoggerContext) LoggerFactory.getILoggerFactory();
        loggerContext.reset();

        rollingFileAppender = new RollingFileAppender<>();
        rollingFileAppender.setContext(loggerContext);
        rollingFileAppender.setAppend(true);
        rollingFileAppender.setFile(logDirectory + "/" + LOG_PREFIX + "-latest.txt");

        SizeAndTimeBasedFNATP<ILoggingEvent> fileNamingPolicy = new SizeAndTimeBasedFNATP<>();
        fileNamingPolicy.setContext(loggerContext);
        fileNamingPolicy.setMaxFileSize(FileSize.valueOf("5MB"));

        TimeBasedRollingPolicy<ILoggingEvent> rollingPolicy = new TimeBasedRollingPolicy<>();
        rollingPolicy.setContext(loggerContext);
        rollingPolicy.setFileNamePattern(logDirectory + "/" + LOG_PREFIX + ".%d{yyyy-MM-dd}.%i.txt");
        rollingPolicy.setMaxHistory(5);
        rollingPolicy.setTimeBasedFileNamingAndTriggeringPolicy(fileNamingPolicy);
        rollingPolicy.setParent(rollingFileAppender);  // parent and context required!
        rollingPolicy.start();

        // Alternative text encoder - very clean pattern, takes up less space
        PatternLayoutEncoder encoder = new PatternLayoutEncoder();
        encoder.setContext(loggerContext);
        encoder.setCharset(Charset.forName("UTF-8"));
//      encoder.setPattern("%date %level [%thread] %msg%n");
        encoder.setPattern("[%thread] %msg%n");
        encoder.start();

        rollingFileAppender.setRollingPolicy(rollingPolicy);
        rollingFileAppender.setEncoder(encoder);
        rollingFileAppender.start();

        // add the newly created appenders to the root logger;
        // qualify Logger to disambiguate from org.slf4j.Logger
        ch.qos.logback.classic.Logger root = (ch.qos.logback.classic.Logger) LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME);
        root.setLevel(Level.DEBUG);
        root.addAppender(rollingFileAppender);

        // print any status messages (warnings, etc) encountered in logback config
        StatusPrinter.print(loggerContext);
    }
## Environment

* **`logback-android` 2:0.0
* **Android version:9.0
* **Platform:**  "Galaxy S8" -->

**Comment by tony19** [comment]
This looks like [LOGBACK-995](https://jira.qos.ch/browse/LOGBACK-995).

See https://github.com/tony19/logback-android/issues/203#issuecomment-528323789 for solution

**Comment by ravsingh-inzura** [comment]
That did the trick.
Many thanks.
