### ISSUE TITLE
Status on Ticket #208

### ISSUE THREAD

**Issue by tiger79** [tony19/logback-android#216]
The ticket #208 adressing logging in Android 10 does not seem to have found his way in a release-version of logback. 
Any change this will happen shortly ? Android 10 is obviously found on many live devices nowadays and having the ability to actually access the log files would be a very desirable use case.

I see that the CircleCI build actually did not go through, so maybe fixing that could result in a new release version ?

**Comment by pischky** [comment]
Not solved until today.
How can I help to solve this?
