### ISSUE TITLE
The problem of log output NUL characters

### ISSUE THREAD

**Issue by ttxz** [tony19/logback-android#222]
When I use `logback-android` recently, there will occasionally be a log printing `NUL` problem. I don't know why? As shown below:
![image](https://user-images.githubusercontent.com/12383775/101740660-1a2d0c80-3b04-11eb-97ff-bd17579f9e26.png)

**Comment by ttxz** [comment]
Is the project still under maintenance? Why are you inactive?

**Comment by tony19** [comment]
Please provide reproduction steps (and a link to a GitHub repo that demonstrates the problem) per the issue template guidelines.

**Comment by ttxz** [comment]
Sorry, I cannot reproduce it! This may happen during system restart or other circumstances, I am not sure! The project is used in a formal project, so there is no demo code.

**Comment by tony19** [comment]
Unfortunately, I can't help without reproduction steps. Feel free to post here when you discover a reliable way to reproduce the issue.
