### ISSUE TITLE
 a lot of tmp files are generated，the device memory card is full

### ISSUE THREAD

**Issue by ronallee** [tony19/logback-android#225]
## Description
The log saving policy is as follows:
maxHistory 7
maxFileSize 10MB
totalSizeCap 500MB
But I don't know why, a lot of tmp files are generated. The size of these tmp files is 10m, which leads to more than 3G logs and the device memory card is full

## Environment

* **`logback-android` version: 
org.slf4j:slf4j-api:1.7.25  
com.github.tony19:logback-android:2.0.0
* **Android version:** 5.1
* **Platform:** 

![image](https://user-images.githubusercontent.com/23241736/110273372-6c000880-8007-11eb-8320-45664a3ee078.png)

**Comment by tony19** [comment]
Please provide reproduction steps and the exact logback config used.

**Comment by tony19** [comment]
Closing due to lack of reproduction
