### ISSUE TITLE
android build error

### ISSUE THREAD

**Issue by LuckyLi706** [tony19/logback-android#226]
## Description

Duplicate class org.slf4j.impl.StaticLoggerBinder found in modules logback-android-2.0.0-runtime.jar (com.github.tony19:logback-android:2.0.0) and slf4j-android-1.7.21.jar (org.slf4j:slf4j-android:1.7.21)
Duplicate class org.slf4j.impl.StaticMDCBinder found in modules logback-android-2.0.0-runtime.jar (com.github.tony19:logback-android:2.0.0) and slf4j-android-1.7.21.jar (org.slf4j:slf4j-android:1.7.21)
Duplicate class org.slf4j.impl.StaticMarkerBinder found in modules logback-android-2.0.0-runtime.jar (com.github.tony19:logback-android:2.0.0) and slf4j-android-1.7.21.jar (org.slf4j:slf4j-android:1.7.21)

Go to the documentation to learn how to Fix dependency resolution errors.

## Environment

* **`logback-android` version: 2.0.0
* **Android version: 9.0
* **Platform:Redmi Note 8 PRO

**Comment by tony19** [comment]
`logback-android` requires `slf4j-api`, not `slf4j-android`, which is a standalone lib. Remove `slf4j-android` to resolve your build error.
