### ISSUE TITLE
Is this library is vulnerable via jndilookup mechanism as in log4j 2.x?

### ISSUE THREAD

**Issue by dineshr93** [tony19/logback-android#230]
Hello

From http://logback.qos.ch/news.html they have made some changes in response to vulnerabilities present in LOG4j
![image](https://user-images.githubusercontent.com/4498415/146183730-0b93ae4f-5981-4cd6-9796-d27695fa4b4b.png)

I'd like to know if this lib is free of such vulnerabilities as well officially.

Thanks.

**Comment by tony19** [comment]
`logback-android` is **not impacted** by this vulnerability because it does not support JNDI.
