### ISSUE TITLE
maxFileSize do'nt take effect, don't support maxFileSize? thanks.

### ISSUE THREAD

**Issue by onunix** [tony19/logback-android#233]
maxFileSize do'nt take effect,  the log file is very big，more than 1MB，reached 1GB，why? thanks.

![image](https://user-images.githubusercontent.com/8155478/149478811-f222a7d9-0717-4ac4-a6b4-2849a9727ae9.png)

**Comment by onunix** [comment]
<rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
            <fileNamePattern>%d{yyyy-MM-dd_HH}.%i.log</fileNamePattern>
        </rollingPolicy>

        <triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
            <maxFileSize>1MB</maxFileSize>
        </triggeringPolicy>

**Comment by onunix** [comment]
here is my code ,it seems maxFileSize do'nt work,

**Comment by tony19** [comment]
Please include all requested details of the bug report. If I don't have enough details to reproduce the problem, this issue will likely be closed. Thanks.

**Comment by onunix** [comment]
android studio 4.2.1
here is my gradle:
    implementation 'org.slf4j:slf4j-api:1.7.25'
    implementation 'com.github.tony19:logback-android:2.0.0'

here is my logback.xml:
<configuration   debug="true">
    <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">

        <file>EmsServer.log</file>
        <triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
            <maxFileSize>5MB</maxFileSize>
        </triggeringPolicy>

        <rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
            <fileNamePattern>EmsServers.%i.log</fileNamePattern>
            <MinIndex>1</MinIndex>
            <MaxIndex>9</MaxIndex>
        </rollingPolicy>
        <encoder>
            <pattern>%msg%n</pattern>
        </encoder>
    </appender>
    <root level="DEBUG">
        <appender-ref ref="FILE" />
    </root>
</configuration>

**Comment by tony19** [comment]
The problem is the file paths specified in `<file>` and `<fileNamePattern>` are not absolute.

Even though by default they're created in the application's internal files directory (`/data/data/__APP_PACKAGE_NAME__/files/`), the files in the config must be specified as absolute paths. You can fix the issue by updating those tags to be:

```html
<appender name="AB2" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <file>/data/data/${PACKAGE_NAME}/files/EmsServer.log</file>
    <triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
        <maxFileSize>1MB</maxFileSize>
    </triggeringPolicy>

    <rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
        <fileNamePattern>/data/data/${PACKAGE_NAME}/files/EmsServers.%i.log</fileNamePattern>
        <minIndex>1</minIndex>
        <maxIndex>9</maxIndex>
    </rollingPolicy>
    <encoder>
        <pattern>%msg%n</pattern>
    </encoder>
</appender>
```
