### ISSUE TITLE
How to append Build Version Number with Log Main File

### ISSUE THREAD

**Issue by JyotiRajwaniya** [tony19/logback-android#242]
Please Provide me solution with this as i have used in my project but need to append build number with file

**Comment by tony19** [comment]
`logback-android` doesn't read the build number, so there's no lib-specific way to do this. It only reads `PACKAGE_NAME`, `VERSION_CODE`, and `VERSION_NAME` from the app's `AndroidManifest.xml`.

It sounds like you just want to log that to a file. You'll have to query the build number in your app, and log it using a `FileAppender`.
