### ISSUE TITLE
Missing SSL parameter configuration

### ISSUE THREAD

**Issue by BrunoLopardo** [tony19/logback-android#250]
## Description
In SSLParametersConfiguration is missing the boolean parameter hostnameVerification (see [logback/SSLParametersConfiguration.java](https://github.com/qos-ch/logback/blob/master/logback-core/src/main/java/ch/qos/logback/core/net/ssl/SSLParametersConfiguration.java)).

**Comment by tony19** [comment]
That feature was [added in `logback` 1.2.7](https://github.com/qos-ch/logback/commit/9b67089750e64cd9f8091a1e9d315fdb527221df). This will be ported to `logback-android` in an upcoming release.
