### ISSUE TITLE
The log cannot be written correctly in the case of multi-process Android application?

### ISSUE THREAD

**Issue by qqdongshao123** [tony19/logback-android#345]
### Describe the bug

我们的App使用了多进程技术，在多进程中每个进程都在往文件中写日志，但是有时候会出现某个进程日志无法成功写入，请问该问题如何解决？谢谢

*Google Translation:*
Our app uses multi-process technology. In the multi-process, each process is writing logs to the file, but sometimes the log of a certain process cannot be written successfully. How to solve this problem? Thanks

### Reproduction

11

### logback-android version

2.0.0

### OS Version

Android 11

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tony19** [comment]
Please provide a reproduction.

**Comment by qqdongshao123** [comment]
May I ask how to solve the problem of multi process log confusion on Android?
