### ISSUE TITLE
How do I configure an AsyncAppender with code?

### ISSUE THREAD

**Issue by ezraroi** [tony19/logback-android#54]
Please provide an example of how to configure the `AsyncAppender` with a `FileAppender` to write to the file in an async way. I am getting many StrictMode policy violations (`StrictModeDiskWriteViolation`) on every log write to my log file.

Thanks.

**Comment by paruntha** [comment]
Quick question about shutting down the AysncAppender
https://github.com/tony19/logback-android/wiki/Appender-Notes#asyncappender

I noticed you said you should call it on the onDestroy method. Would that mean for all the activities and services in live in the same application have this call below on all the onDestory methods?

LoggerContext loggerContext = (LoggerContext) LoggerFactory.getILoggerFactory();
loggerContext.stop();

Is this call even needed?

Dont' think can use the <shutdown/> hook right?
