### ISSUE TITLE
How to configure logs directory

### ISSUE THREAD

**Issue by kirandevarapalli** [tony19/logback-android#58]
Am getting this error while giving the path as '<file>/data/data/com.example/files/log/foo.log</file>
Am having FileNotFoundException

'01-03 16:08:02.466: I/System.out(16808): 16:08:02,459 |-ERROR in ch.qos.logback.core.FileAppender[file] - Failed to create parent directories for [/data/data/com.example/files/log/foo.log]

01-03 16:08:02.466: I/System.out(16808): 16:08:02,460 |-ERROR in ch.qos.logback.core.FileAppender[file] - openFile(/data/data/com.example/files/log/foo.log,true) failed java.io.FileNotFoundException: /data/data/com.example/files/log/foo.log: open failed: ENOENT (No such file or directory)

**Comment by luktar** [comment]
I had similar problem with android 6+. There ware a big changes with permissions. I recommend [`this`](http://stackoverflow.com/questions/40087355/android-mkdirs-not-working) solution.

Good luck!
