### ISSUE TITLE
While using the XML configurations, can we configure the file path dynamically?

### ISSUE THREAD

**Issue by iamkhush** [tony19/logback-android#64]
I am newbie to Android and Java. After going through the examples on http://logback.qos.ch/manual/configuration.html , I see that we can configure the file path. 

I wish to get path from a function written in my code., which basically checks that whether I have permission to read/write on sd card or else on device memory.

How can I do this?

**Comment by xoneill007** [comment]
How does one retrieve these HTML files? Form what I've read, you can from a device emulator in 
 AnrroidStudio- but not from real devices (unless it's rooted).  Or is that the intent? File appender is ideal for DEBUG using emulated devices in AndroidStudio?
