### ISSUE TITLE
Providing a different logback.xml for Release / Debug?

### ISSUE THREAD

**Issue by altdeveloper** [tony19/logback-android#83]
Hi,

I wanted to supply a different logback.xml for Release / Debug, I am using Android Studio so I suppose I could use Product Flavours but it isn't really a product flavor more of a build type.

Does LogBack support loading different xml depending on the build type.

Or is there a better solution?

Anyone have a good working solution ?

Thanks

**Comment by tony19** [comment]
No, not on build type. But you might be able to achieve what you're looking for by setting the [initialization search path](https://github.com/tony19/logback-android#initialization-search-path), where the first included resource found is used (and the rest of the `include` list ignored). `logback-android` always looks for `assets/logback.xml`, and that file could list `assets/logback-debug.xml` and then `assets/logback-release.xml`. In release builds, you would make `assets/logback-debug.xml` unavailable (a pre-build step perhaps?).

##### assets/logback.xml
```xml
<configuration>
    <include resource='assets/logback-debug.xml'/>
    <include resource='assets/logback-release.xml'/>
</configuration>
```

**Comment by altdeveloper** [comment]
Great! Thanks, yes I have included an asset directory below src/debug and src/release (these work as flavours too) and placed a file in each and I am linking as per your instructions and it works! Thanks once again.
