### ISSUE TITLE
Conflicts with proGuard when generating signed APK

### ISSUE THREAD

**Issue by realavaloro** [tony19/logback-android#84]
Hi,

I have noticed an issue that might be related to some of the contents of the dependencies for logback-android, although it could be a proGuard's problem.

I use Android Studio 1.02 with Gradle 1.0.0 to manage dependencies.

The logback.xml has 2 appenders:
**ch.qos.logback.classic.net.SMTPAppender**
and
**ch.qos.logback.core.rolling.RollingFileAppender**

My dependencies, defined in build.gradle are as follows:
```
apply plugin: 'android'
android {
       compileSdkVersion 17
       buildToolsVersion '21.1.2'
 }
dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        compile 'com.android.support:appcompat-v7:19.+'
        compile 'com.google.code.gson:gson:2.3.1'
        compile 'com.github.tony19:logback-android-core:1.1.1-3'
        compile 'com.github.tony19:logback-android-classic:1.1.1-3'
        compile 'org.slf4j:slf4j-api:1.7.10'
}
```
so as you can see the last 3 are the mandatory to use logback.
As I am using the SMTP Appender I need additional javamail-android dependencies https://code.google.com/p/javamail-android/downloads/list
so the 3 JAR are under my `/libs` folder and that's why another dependency is the `dir: 'libs'

If I don't use proGuard, the generated APK contains all the logback dependencies properly and everything is good.
But if I use proGuard, having the following build.gradle instead:
```
apply plugin: 'android'

android {
    compileSdkVersion 17
    buildToolsVersion '21.1.2'
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
    productFlavors {
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:19.+'
    compile 'com.google.code.gson:gson:2.3.1'
    compile 'com.github.tony19:logback-android-core:1.1.1-3'
    compile 'com.github.tony19:logback-android-classic:1.1.1-3'
    compile 'org.slf4j:slf4j-api:1.7.10'
}
```
Then proGuard will fail to generate the signed APK due to some warnings due to some classes. I can disable the warnings on my `proguard-rules.txt` with:
```
-dontwarn org.apache.harmony.awt.**
-dontwarn com.sun.mail.imap.protocol.**
-dontwarn javax.activation.**
```
and then it does not complain anymore, but the generated APK seems to be missing the logback classes, hence when the application runs and the logback.xml is read and the application is trying to instantiate the classes RollingFileAppender or SMTPAppender it causes a Class Not Found Exception.

**Do you know if this is a proGuard issue, Android Studio issue, Gradle issue or it is something incompatible with logback and/or its dependencies?**

There are other dependencies like GSON that are properly included in the APK and work when building it with or without proGuard, so I don't know why the logback wouldn't.

Thank you!

**Comment by tony19** [comment]
Have you included the necessary ProGuard rules to prevent logback classes from being removed?https://github.com/tony19/logback-android#proguard

If I had to guess, I'd say ProGuard is removing the logback classes because your app is not actually using those classes directly but rather is using only the SLF4J API (as you should).

**Comment by realavaloro** [comment]
Hi Tony,

Sorry I must have missed that documentation section about proGuard (I just started using it for first time). It totally makes sense that proGuard is removing logback classes.
Thank you for the link. I'll configure it with the necessary rules.

**Comment by rabidaudio** [comment]
If someone comes looking for this in the future like I did, it is now on the wiki:
https://github.com/tony19/logback-android/wiki#proguard
