### ISSUE TITLE
Threading?

### ISSUE THREAD

**Issue by robertschmid** [tony19/logback-android#85]
I we create a DBAppender in logback-android, will it use the UI thread for logging or does it use a different thread?

**Comment by tony19** [comment]
The `DBAppender` ([`SQLiteAppender`](http://tony19.github.io/logback-android/doc/1.1.1-3/ch/qos/logback/classic/android/SQLiteAppender.html) in the latest version) would log on the same thread it was created on. You'd have to use the [`AsyncAppender`](https://github.com/tony19/logback-android/wiki/Appender-Notes#asyncappender) together in order log asynchronously.
