### ISSUE TITLE
HTTP POST method?

### ISSUE THREAD

**Issue by JDOaktown** [tony19/logback-android#86]
Hi Mr. Tony,
I saw your side project "loggly".

Are there any plans to implement HTTP POST logging to a webserver from android logback?

Thanks for a fantastic product!

**Comment by tony19** [comment]
Hello,

A generic HTTP appender would be relatively easy to implement but is not in my plans for `logback-android`. That actually would be more appropriate as a [`logback-extension`](https://github.com/qos-ch/logback-extensions). If you're interested in Loggly, you should already be able to use `logback-android` with the [Loggly `logback-extension`](https://github.com/qos-ch/logback-extensions/wiki/Loggly).

I'm kind of curious now. How would you use an HTTP appender?

**Comment by JDOaktown** [comment]
RESTFUL webservice.... 
POST method using JSON

see https://github.com/ACRA/acra for comparison...? wondering what you think.

i'm also wondering if you think I could/should tackle this problem (forking you or what?)

**Comment by JDOaktown** [comment]
see http://avilyne.com/?p=105

**Comment by JDOaktown** [comment]
package com.ntier.android.REST;

import java.io.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.security.SecureRandom;
import java.security.cert.CertificateException;
import java.security.cert.X509Certificate;
import java.util.ArrayList;
import java.util.List;

import javax.net.ssl.*;

import org.apache.http.NameValuePair;
import org.apache.http.message.BasicNameValuePair;

import android.content.Context;
import android.content.res.Resources;
import android.os.Message;
import android.util.Log;

import com.google.gson.Gson;
import com.google.gson.stream.JsonWriter;
import com.ntier.android.GAEL1.R;

public class WebServiceGet //extends AsyncTask<String, Integer, String> 
{
	protected final String HTTPS_URL, GET;


	private ArrayList<NameValuePair> params = new ArrayList<NameValuePair>();

	public WebServiceGet(final Context context){
		Resources resources = context.getResources();

		// Populate from res/values/strings.xml
		final String IPaddressServer = resources.getString( R.string.IPaddressServer),
					 ServerPort      = resources.getString( R.string.ServerPort),
					 ServerRESTroot  = resources.getString( R.string.ServerRESTroot);

    //eg.   "https://10.0.0.7:8181/GaelWebSvcGF3/rest/location"
		HTTPS_URL = new StringBuilder("https://") 
						.append( IPaddressServer)
						.append(":")
						.append(ServerPort)
						.append(ServerRESTroot)
						.toString();

		GET = HTTPS_URL + "/sample";
	}//constructor
	
	public void addNameValuePair(String name, String value) {

		params.add(new BasicNameValuePair(name, value));
	}

		
	protected void trustEveryone(boolean trust) {//TODO FOR TESTING/DEV PURPOSE ONLY!!! HIGHLY INSECURE!!!
		// see: http://stackoverflow.com/questions/1217141/self-signed-ssl-acceptance-android/1607997#1607997
		if (!trust) return;

		try {
			HttpsURLConnection
					.setDefaultHostnameVerifier(new HostnameVerifier() {
						public boolean verify(String hostname,
								SSLSession session) {
							return true;
						}
					});
			SSLContext context = SSLContext.getInstance("TLS");
			context.init(null,
					new X509TrustManager[] { new X509TrustManager() {
						public void checkClientTrusted(
								X509Certificate[] chain, String authType)
								throws CertificateException {
						}

						public void checkServerTrusted(
								X509Certificate[] chain, String authType)
								throws CertificateException {
						}

						public X509Certificate[] getAcceptedIssuers() {
							return new X509Certificate[0];
						}
					} }, new SecureRandom());
			HttpsURLConnection.setDefaultSSLSocketFactory(context
					.getSocketFactory());
		} catch (Exception e) { // should never happen
			e.printStackTrace();
		}
	}// trustEveryone


	
	String get(String urlString) {
		String result = "";
		HttpsURLConnection urlConnection = null;
		InputStream in = null;
		try {
			URL url = new URL(GET);
			trustEveryone(true);
			urlConnection = (HttpsURLConnection) url.openConnection();
			//debugging
			InputStream ins = urlConnection.getInputStream();
			in = new BufferedInputStream(ins );
			result = inputStreamToString(in);
			in.close();
		} // TODO Auto-generated catch block
		catch (MalformedURLException e) { e.printStackTrace(); } 
		catch (IOException   e) { e.printStackTrace(); } 
		finally { if (urlConnection != null) urlConnection.disconnect(); }
		
		return result;
	}//get

	
	protected String inputStreamToString(InputStream is) {
		StringBuilder total = new StringBuilder();

		try {
			// Wrap a BufferedReader around the InputStream
			BufferedReader rd = new BufferedReader(
					new InputStreamReader(is));
			String line;
			// Read response until the end
			while ((line = rd.readLine()) != null) {
				total.append(line);
			}
			rd.close();
		} catch (IOException e) {
			Log.e("TAG", e.getLocalizedMessage(), e);
		}

		return total.toString();
	}//inputStreamToString
}//class WebServiceGet


class WebServicePost extends WebServiceGet{
	private final String POST = HTTPS_URL + "/newlocation";

	public WebServicePost(Context mContext) {
		super(mContext);
		//mLocation = location;
	}

	@SuppressWarnings("resource")
	//@Override protected String post(String... urls) {
//	String post(URL url) {
	String post(GaelLocation location) {

		String result = "";
		HttpsURLConnection urlConnection = null;

		
		   try {
			 //URL url = new URL(urls[0]);
			 URL url = new URL(POST);
			 trustEveryone(true);

			 urlConnection = (HttpsURLConnection) url.openConnection();

		     urlConnection.setDoOutput(true);
			 urlConnection.setRequestMethod("POST");
		     urlConnection.setDoOutput(true);
		     urlConnection.setChunkedStreamingMode(0);
		     urlConnection.setRequestProperty("Content-Type","application/json");   

		     urlConnection.connect();
		     //debug
		     OutputStream OUTPUTSTREAM = urlConnection.getOutputStream();
		     OutputStream out = new BufferedOutputStream(OUTPUTSTREAM);
//		     writeJsonStream(out, this.mLocation);
		     
		     writeJsonStream(out, location);//SEND THE PACKET!

		     out.close();
		     InputStream in = new BufferedInputStream(urlConnection.getInputStream());
		     result = inputStreamToString(in);
			} 
		   catch (IOException e) { 
			   e.printStackTrace(); 
			   @SuppressWarnings("null")
			   InputStream errIn = new BufferedInputStream(urlConnection.getErrorStream());
			   result = inputStreamToString(errIn);
		   } 
		   finally { if (urlConnection != null) urlConnection.disconnect(); }

		   return result;
	}//doInBackground

	
	static public void writeJsonStream(OutputStream out, List<Message> messages) throws IOException {
		Gson gson = new Gson();
        JsonWriter writer = new JsonWriter(new OutputStreamWriter(out)); //, "UTF-8"));
        writer.setIndent("  ");
        writer.beginArray();
        for (Message message : messages) {
            gson.toJson(message, Message.class, writer);
        }
        writer.endArray();
        writer.close();
    }

	static public void writeJsonStream(OutputStream out, GaelLocation location) throws IOException {
		Gson gson = new Gson();
        JsonWriter writer = new JsonWriter(new OutputStreamWriter(out)); //, "UTF-8"));
        writer.setIndent("  ");
        gson.toJson(location, GaelLocation.class, writer);
        writer.close();
    }	
}//WebServicePost

**Comment by JDOaktown** [comment]
and an IntentService i think for quick turnaround. A syncadapter will not suffice.

package com.ntier.android.REST;

import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;

import javax.net.ssl.HttpsURLConnection;





import android.app.IntentService;
import android.content.ContentUris;
import android.content.Intent;
import android.net.Uri;
import android.os.IBinder;
import android.support.v4.content.LocalBroadcastManager;
import android.widget.Toast;

public class GAELSyncSvc extends IntentService {

	public static final String 
							   //ACTION_MyIntentService = "com.example.androidintentservice.RESPONSE",
							   //ActionGet = GAELSyncSvc.class.toString() + ".GET",
							   ActionGet = GaelSyncActions.GET.toString(),
							   ActionPost = GaelSyncActions.POST.toString(),
							   
							   EXTRA_KEY_IN = "empty EXTRA_IN",
							   //EXTRA_KEY_OUT = "EXTRA_OUT",
							   RESPONSE = "empty response"
							   ;
	//private static final String HTTPS_URL = "https://10.0.0.7:8181/GaelWebSvcGF3/rest/location";


	
	private enum GaelSyncActions { POST, GET }//GaelSyncActions


	 String extraIn,
	 		extraOut;

//A constructor is required, and must call the super IntentService(String) constructor with a name for the worker thread.
	public GAELSyncSvc() { super( GAELSyncSvc.class.toString() );	}


//The IntentService calls this method from the default worker thread with the intent that started the service.
// When this method returns, IntentService stops the service, as appropriate.
   @Override
	protected void onHandleIntent(Intent intent) {
	   String result = "";
	   Toast.makeText(this, "onHandleIntent Started", 4).show();
//	   Toast.makeText(this, "onHandleIntent Started", Toast.LENGTH_LONG).show();
	   		
	   GaelSyncActions currentAction = GaelSyncActions.valueOf(intent.getAction());

	   	//TODO JAVA 1.6 cannot switch on strings. Refactor switch on strings after upgrading to Java 1.7
   		switch (currentAction) {
           case POST:
			   java.util.Random randomId = new java.util.Random();
			   Uri uri = (Uri) intent.getParcelableExtra("DATA_URI");
			   
			   GaelLocation location = new GaelLocation(randomId.nextLong(),
        			   						    "empty updated",
        			   						    "empty provider",
        			   						    intent.getLongExtra("ALTITUDE", GaelLocation.NoLocation),
        			   						    intent.getLongExtra("LATITUDE", GaelLocation.NoLocation),
        			   						    intent.getLongExtra("LONGITUDE", GaelLocation.NoLocation)
        			   					);
        	   //POST location from uri here
			   long rowid = ContentUris.parseId(uri);
			   result = new WebServicePost(this).post(location);
           break;
           case GET:
   			final String msgFromActivity = intent.getStringExtra(GAELSyncSvc.ActionGet); 
			result = new WebServiceGet(this).get(msgFromActivity);
   			
	        break;
	        default: //TODO handle bad intentAction;
	        	break;
       }//switch

   		Intent intentResponse = new Intent()
									.setAction(ActionGet)
									.putExtra(RESPONSE, result);
		//TODO make the broadcast STICKY
		//TODO consider directed broadcast http://androidtechnicalblog.blogspot.com/2014/01/sending-broadcasts-within-your-app-with.html
		LocalBroadcastManager.getInstance(this).sendBroadcast(intentResponse);

   }//onHandleIntent
   
   

/*	@Override
	public IBinder onBind(Intent intent) {
		//super.onBind(intent);
		throw new UnsupportedOperationException("Not yet implemented");
	}


	@Override
	public void onCreate() {
		super.onCreate();
		Toast.makeText(this, "Service was Created", Toast.LENGTH_LONG).show();

	}

	@Override
	public void onStart(Intent intent, int startId) {
		super.onStart(intent, startId);
		// Perform your long running operations here.
		Toast.makeText(this, "Service Started", Toast.LENGTH_LONG).show();
	}
*/	
	@Override
	public void onDestroy() {
		super.onDestroy();
		Toast.makeText(this, "Service Destroyed", Toast.LENGTH_LONG).show();
	}
}//GAELSyncSvc

**Comment by JDOaktown** [comment]
i'm still working on this...(server pojo)
    @GET
    @Path("exception")
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    @Produces(MediaType.TEXT_PLAIN)
    //@Produces(MediaType.APPLICATION_JSON)
    //public String postException () {
public String postException ( MultivaluedMap<String, String> clientException ) {
    	String retVal = ".exception.";
		System.out.println( retVal );
/*    	boolean debug;
    	Set<String> keyset;
    	int intdebug;
    	keyset = clientException.keySet();
    	intdebug = clientException.size();
    	debug = clientException.isEmpty();
    	for(String keyx : keyset){
    		System.out.println( keyx );
    		}
*/    
    	return retVal;
    	}

**Comment by JDOaktown** [comment]
as you say, not forking but logback-extension github I guess. 
I think I might like tackling this if you think I have the access?

**Comment by tony19** [comment]
Sure, feel free to submit a pull-request to `logback-extensions`.

**Comment by JDOaktown** [comment]
ok. Mr. Tony, I confess I'm not overly familiar w/ github.
This project would me first to contrib on github. I'm familiar w/ customs/procedures/etc.
However I have the tech skill I believe and I like your product so much, feel obligated to pay you but I have ZERO money now, just time to give.

**Comment by JDOaktown** [comment]
I'll need to think a little further on the server side.

**Comment by JDOaktown** [comment]
OOOPS. SORRY. 

i meant to say
 I'M AM NOT AT ALL FAMILIAR W/ GITHUB CUSTOMS/PROCEDURES/ETC./ETC.

**Comment by JDOaktown** [comment]
I would like to speak w/ you if I could. 
I'm just wondering about all of this vs. Loggly......?

**Comment by tony19** [comment]
I believe you're proposing a generic HTTP appender whose endpoint and other attributes (such as method, header, etc.) could be configured. In a way, the Loggly `logback-extension` and `loggly-client` are specializations of the HTTP appender, since they post to a specific HTTP endpoint.

Regarding GitHub pull requests, here's some useful docs: https://help.github.com/articles/using-pull-requests/
