### ISSUE TITLE
Unable to configure logback through AndroidManifest.xml or logback.xml

### ISSUE THREAD

**Issue by tjanson** [tony19/logback-android#89]
I’m having trouble configuring logback in any way, that is, I tried both `AndroidManifest.xml` and `logback.xml`. It’s extremely likely that this is an error on my part (I’m just starting out with Android), but I can’t work it out.

I’m using Android Studio; start a new project, modify `MainActivity.java` to minimal example:

```java
package com.tomjanson.logbacktest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import android.app.Activity;
import android.os.Bundle;

public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // SLF4J
        Logger log = LoggerFactory.getLogger(MainActivity.class);
        log.info("hello world");
    }
}
```

And add `<logback>` section to `AndroidManifest.xml` (note the `FOOBAR`):

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.tomjanson.logbacktest" >

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" >
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

    <logback>
        <configuration>
            <appender
                name="LOGCAT"
                class="ch.qos.logback.classic.android.LogcatAppender" >
                <tagEncoder>
                    <pattern>%logger{0}</pattern>
                </tagEncoder>
                <encoder>
                    <pattern>FOOBAR [ %thread ] %msg%n</pattern>
                </encoder>
            </appender>

            <root level="WARN" >
                <appender-ref ref="LOGCAT" />
            </root>
        </configuration>
    </logback>

</manifest>
```

Actual Logcat output:

> `03-07 22:38:37.988  14412-14412/com.tomjanson.logbacktest I/System.out﹕ 22:38:37.986 [main] INFO  c.tomjanson.logbacktest.MainActivity - hello world`

Expected: None (due to loglevel being `WARN`), or something including "FOOBAR".

I also tried placing a `logback.xml` in `app/src/main/assets/` and lots of other places, same thing.

Am I doing something fundamentally wrong here?

**Comment by tony19** [comment]
The `I/System.out` tag suggests to me that you might be using `slf4j-android` instead of `slf4j-api`. The former is a standalone logging framework while the latter is the API required by `logback-android`. You can't have both `slf4j-android` and `slf4j-api` in your classpath.

**Comment by tjanson** [comment]
Apparently the problem is that I don’t know how to include libraries in Android Studio (it’s my first project). So feel free to close this as invalid and I’ll seek help elsewhere. But maybe you know what I’m doing wrong:

I tried both "Project Structure → Dependencies → + → Library Dependency", and "… → File Dependency", resulting in

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'org.slf4j:slf4j-api:1.7.10'
    compile 'com.github.tony19:logback-android-core:1.1.1-3'
    compile 'com.github.tony19:logback-android-classic:1.1.1-3'
}
```
and
```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile files('libs/logback-android-1.1.1-3.jar')
    compile files('libs/slf4j-api-1.7.6.jar')
}
```
respectively, as well as without `compile fileTree(dir: 'libs', include: ['*.jar'])`. No luck. Adding libraries to Gradle/Android Studio seems to be sufficiently difficult to have spawned [dozens of StackOverflow questions](https://stackoverflow.com/search?tab=votes&q=android%20studio%20library), but I still can’t figure it out. :(

**Comment by tony19** [comment]
I was unsuccessful in configuring logback from AndroidManifest.xml when debugging through Android Studio, but I was able to use file-based configuration:

 1. In Android Studio's Project pane, right-click your *app* directory, and choose *New > Folder > Assets Folder*.
 2. On the next screen, click *Finish*.
 3. Right-click on the *assets* folder, and choose *New > File*
 4. Name it *logback.xml*.
 5. Copy your logback configuration there.

**Comment by tjanson** [comment]
Thank you! Not sure whether it was the `exclude module: 'android'` or the config file that made the difference, but it works now. Thanks again :)

**Comment by tony19** [comment]
The problem was most likely the inability to read logback configs from `AndroidManifest.xml` when using Android Studio. The `exclude module: 'android'` prevents a transitive dependency on the Android 2.1 SDK when pulling in `logback-android`.
