### ISSUE TITLE
NetworkOnMainThreadException when SocketAppender host is a domain name

### ISSUE THREAD

**Issue by tjanson** [tony19/logback-android#90]
I’m successfully using a `SocketAppender` to log to a remote server when the host is set as an IP address. However, when specifying a domain name as host (otherwise identical configuration), I get a `NetworkOnMainThreadExcept` during startup. Possible problem: The “Lazy” setting does not seem to work.

The configuration file (and in fact the entire project) is [here on Github](https://github.com/tjanson/WifiLocationLogger/blob/master/app/src/main/assets/logback.xml#L5); [Log showing the exception](https://gist.github.com/tjanson/bf35f61a23ebd51557e3#file-logback-networkonmainthread-L30), excerpt:

```
03-14 23:21:13.927 32036-32036/com.tomjanson.wifilocationlogger I/System.out﹕ 23:21:13,927 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.net.SocketAppender]
03-14 23:21:13.930 32036-32036/com.tomjanson.wifilocationlogger I/System.out﹕ 23:21:13,930 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [SOCKET]
03-14 23:21:13.938 32036-32036/com.tomjanson.wifilocationlogger I/System.out﹕ 23:21:13,938 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@57:15 - no applicable action for [lazy], current ElementPath is [[configuration][appender][lazy]]
03-14 23:21:13.967 32036-32036/com.tomjanson.wifilocationlogger I/System.out﹕ 23:21:13,965 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@63:16 - RuntimeException in Action for tag [appender] android.os.NetworkOnMainThreadException
```

**Comment by gauravdott** [comment]
Same problem. Did you figure out the solution?

**Comment by tjanson** [comment]
I worked around it by simply entering my server’s (thankfully static) IP address.

**Comment by gauravdott** [comment]
ok, that's not an option for me

**Comment by tony19** [comment]
@gauravdott, Indeed, the lazy flag was unintentionally removed during a merge from the main logback project that completely rewrote the `SocketAppender`. I started to restore that feature in a [branch(https://github.com/tony19/logback-android/tree/socket-appender-lazy-flag).

**Comment by tony19** [comment]
A possible workaround is to use `AsyncAppender` as seen with this [`SocketAppender` example](https://github.com/tony19/logback-android/wiki/Appender-Notes#socketappender-syslogappender). Let me know if that helps.

**Comment by tony19** [comment]
Closing this stale issue, as there's workaround in place (see previous comment). Please create a new issue if the issue resurfaces.
