### ISSUE TITLE
Line Break and log patterns

### ISSUE THREAD

**Issue by AssafMashiah** [tony19/logback-android#92]
Hey, I am using this as a pattern:
private final static String PATTERN = "%logger{36}: %d{"+ Time.TIME_FORMAT + "} - %msg%n";

For some reason I am not getting a line break once I read the file - Any ideas?

**Comment by tony19** [comment]
Can you provide additional reproduction steps? There's not enough context for me to determine the problem because that pattern correctly appends a new-line in my tests with a `RollingFileAppender` (`logback-android-1.1.1-3.jar` and `slf4j-api-1.7.7.jar`).

Please indicate the version of `logback-android` and `slf4j-api`, and provide a code snippet of your configuration.

**Comment by tony19** [comment]
I'm assuming you resolved the issue yourself. Feel free to comment otherwise.

**Comment by AssafMashiah** [comment]
Thanks for the reply and sorry I was not available. I was using the latest maven (gradle) build as well as the slf4j api.
The issue was that while I was reading the file the line break was not there for some reason. 

But yea, I made some workaround it - thank you anyway

**Comment by tony19** [comment]
Can you provide your code to reproduce the problem?

**Comment by AssafMashiah** [comment]
This is it:
`private final static String PATTERN = "%d{"+ Time.TIME_FORMAT + "} - %msg%n";`
...
`RollingFileAppender<ILoggingEvent> rollingFileAppender = new RollingFileAppender<>();
        rollingFileAppender.setAppend(true);
        rollingFileAppender.setContext(lc);
        rollingFileAppender.setFile(LOG_FILE_PATH);

        SizeBasedTriggeringPolicy<ILoggingEvent> sizeBased = new SizeBasedTriggeringPolicy<>();
        sizeBased.setContext(lc);
        // Todo: Needs testing
        sizeBased.setMaxFileSize("4mb");
        sizeBased.start();
        rollingFileAppender.setTriggeringPolicy(sizeBased);

        LogbackRollingPolicy logbackRollingPolicy = new LogbackRollingPolicy();
        logbackRollingPolicy.setFileNamePattern("RX%i.txt");
        // parent and context required!
        logbackRollingPolicy.setParent(rollingFileAppender);
        logbackRollingPolicy.setContext(lc);
        logbackRollingPolicy.start();
        rollingFileAppender.setRollingPolicy(logbackRollingPolicy);

        PatternLayoutEncoder encoderFile = new PatternLayoutEncoder();
        encoderFile.setContext(lc);
        encoderFile.setPattern(PATTERN);
        encoderFile.start();
        rollingFileAppender.setEncoder(encoderFile);

        rollingFileAppender.start();`

Thanks

**Comment by tony19** [comment]
That's basically the same code I have, but it works for me. See the example here: https://github.com/tony19/logback-examples/blob/master/logback-android/rolling-file-appender/app/src/main/java/com/github/tony19/rollingfileappender/MainActivity.java

What was your workaround?
