### ISSUE TITLE
no output to the console if i use JUnit tests

### ISSUE THREAD

**Issue by HowardSchmaeu** [tony19/logback-android#93]
what i have to do to see the output to the console if i use JUnit tests?? If i go with the "normal" Android Tests i can see the Output but if i use JUnit Tests i see nothing... how can i do that??

I DON'T use Robolectric.. :-D

**Comment by tony19** [comment]
I assume you're referring to stdout from unit tests when building from the command line. Correct? If so, the stdout is redirected into a file by default. To disable the redirect, you can set this flag from the command line:

```
mvn test -Dmaven.test.redirectTestOutputToFile=false
```

or delete it from [`pom.xml`:59](https://github.com/tony19/logback-android/blob/ee6932c22c906788442aed063351d0cb53b542a9/pom.xml#L59).

**Comment by HowardSchmaeu** [comment]
THANK YOU!!
