### ISSUE TITLE
How to configure it in an Android Library Project?

### ISSUE THREAD

**Issue by cfan8** [tony19/logback-android#95]
Hi, I'm wondering how can I use logback-android in an Android Library Project. So here is my Android Project structure:
* AndroidLibraryDemo
  * MyLibraryProject
    * assets/logback.xml
    * src
    * res
    * AndroidManifest.xml (of library project)
  * src
  * res
  * AndroidManifest.xml (of demo project)

And it doesn't work as expected. But I can't move the configuration file to the Demo project as it is meant to be used for illustration only. I can't put it into AndroidManifest.xml of the library project as the content of it will be ignored from the application perspective.
I'm wondering how can I achieve this: publish my project as a library project and the logging functionality does not rely on any assumptions of the application project.

**Comment by tony19** [comment]
You'd have to use code-based configuration to load the XML file from a specified path, as shown in the example below.

https://github.com/tony19/logback-android#configuration-in-code
```java
private void configureLogbackByFilePath() {
  // reset the default context (which may already have been initialized)
  // since we want to reconfigure it
  LoggerContext lc = (LoggerContext)LoggerFactory.getILoggerFactory();
  lc.reset();

  JoranConfigurator config = new JoranConfigurator();
  config.setContext(lc);

  try {
    config.doConfigure("/path/to/config.xml");
  } catch (JoranException e) {
    e.printStackTrace();
  }
}
```
