### ISSUE TITLE
NetworkOnMainThreadException with loggly in Android Native application

### ISSUE THREAD

**Issue by keyuraashra** [tony19/logback-android#97]
I am getting NetworkOnMainThreadException with loggly in my android application.

I have a query here - 

Can't we log on main thread using loggly? If that is the case then only logs on background thread will be logged on loggly or after the exception it won't write any logs on loggly?

This is my configuration logback.xmk :-

<configuration debug="true">

    <appender name="LOGCAT" class="ch.qos.logback.classic.android.LogcatAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <appender name="loggly" class="ch.qos.logback.ext.loggly.LogglyAppender">
        <endpointUrl>
            http://logs-01.loggly.com/inputs/xxx-xxx-xxx-xxx/tag/logback
        </endpointUrl>
        <pattern>%d{"ISO8601", UTC} %p %t %c{0}.%M - %m%n</pattern>
    </appender>

    <root level="debug">
        <appender-ref ref="LOGCAT" />
        <appender-ref ref="loggly" />
    </root>
</configuration>

Error:-

librarytest I/System.out﹕ 17:42:48,126 |-ERROR in ch.qos.logback.ext.loggly.LogglyAppender[loggly] - Appender [loggly] failed to append. android.os.NetworkOnMainThreadException
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at android.os.NetworkOnMainThreadException
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at java.net.InetAddress.getAllByName(InetAddress.java:215)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at com.android.okhttp.HostResolver$1.getAllByName(HostResolver.java:29)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:232)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:124)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:272)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at ch.qos.logback.ext.loggly.LogglyAppender.postToLoggly(Unknown Source)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at ch.qos.logback.ext.loggly.LogglyAppender.append(Unknown Source)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(Unknown Source)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(Unknown Source)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Unknown Source)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at ch.qos.logback.classic.Logger.callAppenders(Unknown Source)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Unknown Source)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at ch.qos.logback.classic.Logger.filterAndLog_1(Unknown Source)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at ch.qos.logback.classic.Logger.debug(Unknown Source)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at co.pointwise.android.sdk.services.WifiService.startWifiUpdate(WifiService.java:221)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at co.pointwise.android.sdk.services.WifiService.onStartCommand(WifiService.java:49)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2896)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at android.app.ActivityThread.access$2100(ActivityThread.java:148)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1390)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at android.os.Looper.loop(Looper.java:135)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at android.app.ActivityThread.main(ActivityThread.java:5312)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at java.lang.reflect.Method.invoke(Native Method)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at java.lang.reflect.Method.invoke(Method.java:372)
08-13 17:42:48.128  25793-25793/co.librarytest I/System.out﹕ at 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)

**Comment by keyuraashra** [comment]
I have removed all the logs from main thread and tested again. Still getting error,

08-13 19:01:19.524  25096-27420/co.librarytest I/System.out﹕ 19:01:19,523 |-ERROR in ch.qos.logback.ext.loggly.LogglyAppender[loggly] - Appender [loggly] failed to append. java.lang.NullPointerException: Attempt to invoke virtual method 'com.android.okhttp.Route com.android.okhttp.Connection.getRoute()' on a null object reference
08-13 19:01:19.525  25096-27420/co.librarytest I/System.out﹕ at 	at ch.qos.logback.ext.loggly.LogglyAppender.postToLoggly(Unknown Source)

Any idea how to resolve it?

**Comment by JasonSheedy** [comment]
I'm experiencing the same problem trying to send logs to papertrail. There are a few suggestions around online that applying a looser thread policy should help, but I don't know how this can be applied to the logback intialisation or if it's safe to do so.

```
StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
StrictMode.setThreadPolicy(policy);
```

**Comment by tony19** [comment]
@keyuraashra, Right, you cannot use any loggers that write to the network on the main thread without disabling StrictMode as @JasonSheedy points out. You should be using `AsyncAppender` for that (see [example](https://github.com/tony19/logback-android/wiki/Appender-Notes#socketappender-syslogappender)).

**Comment by tony19** [comment]
I'm not yet sure about the NPE you're seeing. I'll take a look this weekend.

**Comment by JasonSheedy** [comment]
@tony19 Thanks for the tip on `AsyncAppender` .. looks like it's exactly what I was looking for.

**Comment by tony19** [comment]
@keyuraashra, It looks like a bug in OkHttp based on the stacktraces I'm getting. The issue doesn't appear to be related to logback-android, so I'm closing it. We can continue any investigations in logback-ext-loggly.

When using Loggly's http endpoint:
```
21:22:27,020 |-ERROR in ch.qos.logback.ext.loggly.LogglyAppender[loggly] - IOException while attempting to communicate with Loggly java.net.SocketException: sendto failed: EBADF (Bad file descriptor)
    at java.net.SocketException: sendto failed: EBADF (Bad file descriptor)
    at 	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:542)
    at 	at libcore.io.IoBridge.sendto(IoBridge.java:511)
    at 	at java.net.PlainSocketImpl.write(PlainSocketImpl.java:500)
    at 	at java.net.PlainSocketImpl.-wrap1(PlainSocketImpl.java)
    at 	at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
    at 	at com.android.okhttp.okio.Okio$1.write(Okio.java:76)
    at 	at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
    at 	at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:221)
    at 	at com.android.okhttp.internal.http.HttpConnection.flush(HttpConnection.java:141)
    at 	at com.android.okhttp.internal.http.HttpTransport.finishRequest(HttpTransport.java:52)
    at 	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:902)
    at 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
    at 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:439)
    at 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384)
    at 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
    at 	at ch.qos.logback.ext.loggly.LogglyAppender.postToLoggly(Unknown Source)
    at 	at ch.qos.logback.ext.loggly.LogglyAppender.append(Unknown Source)
    at 	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(Unknown Source)
    at 	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(Unknown Source)
    at 	at ch.qos.logback.core.AsyncAppenderBase$Worker.run(Unknown Source)
Caused by: android.system.ErrnoException: sendto failed: EBADF (Bad file descriptor)
    at 	at libcore.io.Posix.sendtoBytes(Native Method)
    at 	at libcore.io.Posix.sendto(Posix.java:211)
    at 	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
    at 	at libcore.io.IoBridge.sendto(IoBridge.java:509)
	at 	... 18 common frames omitted
```

When using Loggly's https endpoint:
```
20:51:39,050 |-ERROR in ch.qos.logback.ext.loggly.LogglyAppender[loggly] - IOException while attempting to communicate with Loggly java.net.SocketException: Socket is closed
   at java.net.SocketException: Socket is closed
   at 	at com.android.org.conscrypt.OpenSSLSocketImpl.checkOpen(OpenSSLSocketImpl.java:247)
   at 	at com.android.org.conscrypt.OpenSSLSocketImpl.-wrap0(OpenSSLSocketImpl.java)
   at 	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:756)
   at 	at com.android.okhttp.okio.Okio$1.write(Okio.java:76)
   at 	at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
   at 	at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:221)
   at 	at com.android.okhttp.internal.http.HttpConnection.flush(HttpConnection.java:141)
   at 	at com.android.okhttp.internal.http.HttpTransport.finishRequest(HttpTransport.java:52)
   at 	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:902)
   at 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
   at 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:439)
   at 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384)
   at 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
   at 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
   at 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
   at 	at ch.qos.logback.ext.loggly.LogglyAppender.postToLoggly(Unknown Source)
   at 	at ch.qos.logback.ext.loggly.LogglyAppender.append(Unknown Source)
   at 	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(Unknown Source)
   at 	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(Unknown Source)
   at 	at ch.qos.logback.core.AsyncAppenderBase$Worker.run(Unknown Source)
```

**Comment by bgerstle** [comment]
@tony19 I'm still seeing this using okhttp3.4.1 (which should contain that fix, as it's quite old now):

```
09-12 15:26:38.849 29066-29131/io.lookback.awesome I/System.out: 15:26:38,840 |-ERROR in ch.qos.logback.ext.loggly.LogglyAppender[loggly] - IOException while attempting to communicate with Loggly java.net.SocketException: Socket is closed
09-12 15:26:38.849 29066-29131/io.lookback.awesome I/System.out: 	at java.net.SocketException: Socket is closed
```

configuration:

```
<configuration debug="true">
    <appender name="logcat" class="ch.qos.logback.classic.android.LogcatAppender">
        <tagEncoder>
            <pattern>%logger{12}</pattern>
        </tagEncoder>
        <encoder>
            <pattern>[%-20thread] %msg</pattern>
        </encoder>
        <pattern>FOO %d{"ISO8601", UTC}  %p %t %c{0}.%M - %m%n</pattern>
    </appender>

    <appender name="loggly" class="ch.qos.logback.ext.loggly.LogglyAppender">
        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>WARN</level>
        </filter>
        <pattern>%d{"ISO8601", UTC}  %p %t %c{0}.%M - %m%n</pattern>
        <endpointUrl>https://logs-01.loggly.com/inputs/[redacted]/tag/android-awesome</endpointUrl>
    </appender>

    <appender name="async-loggly" class="ch.qos.logback.classic.AsyncAppender">
        <appender-ref ref="loggly" />
    </appender>

    <root level="DEBUG">
        <appender-ref ref="logcat" />
        <appender-ref ref="async-loggly" />
    </root>
</configuration>
```

Strangely, when I try to set a breakpoint for the exception or the method that calls it, the breakpoints are never hit.  🤔

**Comment by bgerstle** [comment]
And here's logback config debug output:

```
09-12 15:26:15.364 29066-29066/io.lookback.awesome I/System.out: 15:26:15,308 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [assets/logback.xml] at [assets/logback.xml]
09-12 15:26:15.365 29066-29066/io.lookback.awesome I/System.out: 15:26:15,364 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.android.LogcatAppender]
09-12 15:26:15.368 29066-29066/io.lookback.awesome I/System.out: 15:26:15,368 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [logcat]
09-12 15:26:15.382 29066-29066/io.lookback.awesome I/System.out: 15:26:15,381 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [tagEncoder] property
09-12 15:26:15.431 29066-29066/io.lookback.awesome I/System.out: 15:26:15,430 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
09-12 15:26:15.449 29066-29066/io.lookback.awesome I/System.out: 15:26:15,449 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@9:18 - no applicable action for [pattern], current ElementPath  is [[configuration][appender][pattern]]
09-12 15:26:15.450 29066-29066/io.lookback.awesome I/System.out: 15:26:15,450 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.ext.loggly.LogglyAppender]
09-12 15:26:15.466 29066-29066/io.lookback.awesome I/System.out: 15:26:15,466 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [loggly]
09-12 15:26:15.500 29066-29066/io.lookback.awesome I/System.out: 15:26:15,500 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
09-12 15:26:15.503 29066-29066/io.lookback.awesome I/System.out: 15:26:15,503 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [async-loggly]
09-12 15:26:15.504 29066-29066/io.lookback.awesome I/System.out: 15:26:15,504 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [loggly] to ch.qos.logback.classic.AsyncAppender[async-loggly]
09-12 15:26:15.504 29066-29066/io.lookback.awesome I/System.out: 15:26:15,504 |-INFO in ch.qos.logback.classic.AsyncAppender[async-loggly] - Attaching appender named [loggly] to AsyncAppender.
09-12 15:26:15.505 29066-29066/io.lookback.awesome I/System.out: 15:26:15,505 |-INFO in ch.qos.logback.classic.AsyncAppender[async-loggly] - Setting discardingThreshold to 51
09-12 15:26:15.506 29066-29066/io.lookback.awesome I/System.out: 15:26:15,506 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
09-12 15:26:15.506 29066-29066/io.lookback.awesome I/System.out: 15:26:15,506 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [logcat] to Logger[ROOT]
09-12 15:26:15.506 29066-29066/io.lookback.awesome I/System.out: 15:26:15,506 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [async-loggly] to Logger[ROOT]
09-12 15:26:15.507 29066-29066/io.lookback.awesome I/System.out: 15:26:15,507 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
09-12 15:26:15.507 29066-29066/io.lookback.awesome I/System.out: 15:26:15,507 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@89abd7 - Registering current configuration as safe fallback point
```
