### ISSUE TITLE
AsyncAppender documentation flaw

### ISSUE THREAD

**Issue by dral3x** [tony19/logback-android#98]
Hello there,

Working with `AsyncAppender` I encounter an issue. `AsyncAppender` supports only 1 appender. This is not obvious until I look at the source code of `addAppender`.

I think we should highlight this point in the docs, to avoid loosing more hours of work around this limitation :+1: 

Alessandro

**Comment by tony19** [comment]
Sure, propose an update? :)

**Comment by dral3x** [comment]
There are 2 kind of possible solution here.
- let the async handler supports more than one appender
- document and add some logs/warning in the code to force the current behaviour.

What do you think about?

**Comment by tony19** [comment]
The `AsyncAppender` in `logback` proper also only takes one child appender (as *vaguely* indicated in the [`logback` manual](https://logback.qos.ch/manual/appenders.html#AsyncAppender)). I think it would be best to keep the API for this appender in sync with `logback` proper, so I've simply documented this limitation in the [wiki](https://github.com/tony19/logback-android/wiki/Appender-Notes/c183b4672deed277600c768f571fa50306c125a1).

**Comment by dral3x** [comment]
Thanks @tony19 👍
